using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Medical
{
    public enum Features
    {
        ANOMALOUS_MEDICAL_KEY = 0,
        PIPER_JBO_MODULE = 1,
        PIPER_JBO_WIZARD_DOPPLER = 2,
        PIPER_JBO_WIZARD_DENTITION = 3,
        PIPER_JBO_WIZARD_CEPHALOMETRIC = 4,
        PIPER_JBO_WIZARD_MANDIBLE = 5,
        PIPER_JBO_WIZARD_DISC_CLOCK = 6,
        PIPER_JBO_WIZARD_DISC_SPACE = 7,
        PIPER_JBO_WIZARD_CEPHALOMETRIC_DENTITION = 8,
        PIPER_JBO_WIZARD_CLINICAL_DOPPLER = 9,
        PIPER_JBO_WIZARD_RADIOGRAPHY = 10,
        PIPER_JBO_WIZARD_MRI = 11,
        PIPER_JBO_VERSION_DOPPLER = 12,
        PIPER_JBO_VERSION_DENTITION_PROFILE = 13,
        PIPER_JBO_VERSION_CLINICAL = 14,
        PIPER_JBO_VERSION_RADIOGRAPHY_CT = 15,
        PIPER_JBO_VERSION_MRI = 16,
        PIPER_JBO_VERSION_GRAPHICS = 17,
        PIPER_JBO_FEATURE_CUSTOM_LAYERS = 18,
        PIPER_JBO_FEATURE_FULL_RENDERING = 19,
        PIPER_JBO_FEATURE_CLONE_WINDOW = 20,
        PIPER_JBO_FEATURE_SIMULATION = 21,
    }
}
