//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medical.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AdaptationIcon {
            get {
                object obj = ResourceManager.GetObject("AdaptationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AdaptBottomTeeth {
            get {
                object obj = ResourceManager.GetObject("AdaptBottomTeeth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AdaptLeftLateral {
            get {
                object obj = ResourceManager.GetObject("AdaptLeftLateral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AdaptLeftMidAnterior {
            get {
                object obj = ResourceManager.GetObject("AdaptLeftMidAnterior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AdaptMidlineAnterior {
            get {
                object obj = ResourceManager.GetObject("AdaptMidlineAnterior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AdaptRightLateral {
            get {
                object obj = ResourceManager.GetObject("AdaptRightLateral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AdaptRightMidAnterior {
            get {
                object obj = ResourceManager.GetObject("AdaptRightMidAnterior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AdaptTopTeeth {
            get {
                object obj = ResourceManager.GetObject("AdaptTopTeeth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomTeethRemove {
            get {
                object obj = ResourceManager.GetObject("BottomTeethRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTWizardLarge {
            get {
                object obj = ResourceManager.GetObject("CTWizardLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationLeftCondyle {
            get {
                object obj = ResourceManager.GetObject("DegenerationLeftCondyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationLeftCondyleDistorted {
            get {
                object obj = ResourceManager.GetObject("DegenerationLeftCondyleDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationLeftCondyleLateralPole {
            get {
                object obj = ResourceManager.GetObject("DegenerationLeftCondyleLateralPole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationLeftCondyleLateralPoleDistorted {
            get {
                object obj = ResourceManager.GetObject("DegenerationLeftCondyleLateralPoleDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationLeftCondyleMedialPole {
            get {
                object obj = ResourceManager.GetObject("DegenerationLeftCondyleMedialPole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationLeftCondyleMedialPoleDistorted {
            get {
                object obj = ResourceManager.GetObject("DegenerationLeftCondyleMedialPoleDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationRightCondyle {
            get {
                object obj = ResourceManager.GetObject("DegenerationRightCondyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationRightCondyleDistorted {
            get {
                object obj = ResourceManager.GetObject("DegenerationRightCondyleDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationRightCondyleLateralPole {
            get {
                object obj = ResourceManager.GetObject("DegenerationRightCondyleLateralPole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationRightCondyleLateralPoleDistorted {
            get {
                object obj = ResourceManager.GetObject("DegenerationRightCondyleLateralPoleDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationRightCondyleMedialPole {
            get {
                object obj = ResourceManager.GetObject("DegenerationRightCondyleMedialPole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegenerationRightCondyleMedialPoleDistorted {
            get {
                object obj = ResourceManager.GetObject("DegenerationRightCondyleMedialPoleDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DopplerWizardLarge {
            get {
                object obj = ResourceManager.GetObject("DopplerWizardLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExploreIconSmall {
            get {
                object obj = ResourceManager.GetObject("ExploreIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftAntegonialNotch {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftAntegonialNotch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftAntegonialNotchDistorted {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftAntegonialNotchDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftCondyleHeight {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftCondyleHeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftCondyleHeightSmall {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftCondyleHeightSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftCondyleRotation {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftCondyleRotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftCondyleRotationRotated {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftCondyleRotationRotated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftMandibularNotch {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftMandibularNotch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftMandibularNotchDistorted {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftMandibularNotchDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftRamusHeight {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftRamusHeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthLeftRamusHeightSmall {
            get {
                object obj = ResourceManager.GetObject("GrowthLeftRamusHeightSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightAntegonialNotch {
            get {
                object obj = ResourceManager.GetObject("GrowthRightAntegonialNotch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightAntegonialNotchDistorted {
            get {
                object obj = ResourceManager.GetObject("GrowthRightAntegonialNotchDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightCondyleHeight {
            get {
                object obj = ResourceManager.GetObject("GrowthRightCondyleHeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightCondyleHeightSmall {
            get {
                object obj = ResourceManager.GetObject("GrowthRightCondyleHeightSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightCondyleRotation {
            get {
                object obj = ResourceManager.GetObject("GrowthRightCondyleRotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightCondyleRotationRotated {
            get {
                object obj = ResourceManager.GetObject("GrowthRightCondyleRotationRotated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightMandibularNotch {
            get {
                object obj = ResourceManager.GetObject("GrowthRightMandibularNotch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightMandibularNotchDistorted {
            get {
                object obj = ResourceManager.GetObject("GrowthRightMandibularNotchDistorted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightRamusHeight {
            get {
                object obj = ResourceManager.GetObject("GrowthRightRamusHeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowthRightRamusHeightSmall {
            get {
                object obj = ResourceManager.GetObject("GrowthRightRamusHeightSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftCondyleDegeneration {
            get {
                object obj = ResourceManager.GetObject("LeftCondyleDegeneration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftCondyleGrowth {
            get {
                object obj = ResourceManager.GetObject("LeftCondyleGrowth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDiscBoneOnBone {
            get {
                object obj = ResourceManager.GetObject("LeftDiscBoneOnBone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDiscOpen {
            get {
                object obj = ResourceManager.GetObject("LeftDiscOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDiscPosition {
            get {
                object obj = ResourceManager.GetObject("LeftDiscPosition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDiscSpace {
            get {
                object obj = ResourceManager.GetObject("LeftDiscSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftFossaFlat {
            get {
                object obj = ResourceManager.GetObject("LeftFossaFlat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftFossaFlatness {
            get {
                object obj = ResourceManager.GetObject("LeftFossaFlatness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftFossaNormal {
            get {
                object obj = ResourceManager.GetObject("LeftFossaNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MRIWizardLarge {
            get {
                object obj = ResourceManager.GetObject("MRIWizardLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NotesIcon {
            get {
                object obj = ResourceManager.GetObject("NotesIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProfileIcon {
            get {
                object obj = ResourceManager.GetObject("ProfileIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProfileLeftLateral {
            get {
                object obj = ResourceManager.GetObject("ProfileLeftLateral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProfileLeftMidLateral {
            get {
                object obj = ResourceManager.GetObject("ProfileLeftMidLateral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProfileMidline {
            get {
                object obj = ResourceManager.GetObject("ProfileMidline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProfileRightLateral {
            get {
                object obj = ResourceManager.GetObject("ProfileRightLateral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProfileRightMidLateral {
            get {
                object obj = ResourceManager.GetObject("ProfileRightMidLateral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ResizeDownSmall {
            get {
                object obj = ResourceManager.GetObject("ResizeDownSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ResizeUpSmall {
            get {
                object obj = ResourceManager.GetObject("ResizeUpSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightCondyleDegeneration {
            get {
                object obj = ResourceManager.GetObject("RightCondyleDegeneration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightCondyleGrowth {
            get {
                object obj = ResourceManager.GetObject("RightCondyleGrowth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDiscBoneOnBone {
            get {
                object obj = ResourceManager.GetObject("RightDiscBoneOnBone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDiscOpen {
            get {
                object obj = ResourceManager.GetObject("RightDiscOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDiscPosition {
            get {
                object obj = ResourceManager.GetObject("RightDiscPosition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDiscSpace {
            get {
                object obj = ResourceManager.GetObject("RightDiscSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightFossaFlat {
            get {
                object obj = ResourceManager.GetObject("RightFossaFlat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightFossaFlatness {
            get {
                object obj = ResourceManager.GetObject("RightFossaFlatness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightFossaNormal {
            get {
                object obj = ResourceManager.GetObject("RightFossaNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveSmall {
            get {
                object obj = ResourceManager.GetObject("SaveSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TeethWizardIcon {
            get {
                object obj = ResourceManager.GetObject("TeethWizardIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth1 {
            get {
                object obj = ResourceManager.GetObject("tooth1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth10 {
            get {
                object obj = ResourceManager.GetObject("tooth10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth10removed {
            get {
                object obj = ResourceManager.GetObject("tooth10removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth11 {
            get {
                object obj = ResourceManager.GetObject("tooth11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth11removed {
            get {
                object obj = ResourceManager.GetObject("tooth11removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth12 {
            get {
                object obj = ResourceManager.GetObject("tooth12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth12removed {
            get {
                object obj = ResourceManager.GetObject("tooth12removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth13 {
            get {
                object obj = ResourceManager.GetObject("tooth13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth13removed {
            get {
                object obj = ResourceManager.GetObject("tooth13removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth14 {
            get {
                object obj = ResourceManager.GetObject("tooth14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth14removed {
            get {
                object obj = ResourceManager.GetObject("tooth14removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth15 {
            get {
                object obj = ResourceManager.GetObject("tooth15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth15removed {
            get {
                object obj = ResourceManager.GetObject("tooth15removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth16 {
            get {
                object obj = ResourceManager.GetObject("tooth16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth16removed {
            get {
                object obj = ResourceManager.GetObject("tooth16removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth17 {
            get {
                object obj = ResourceManager.GetObject("tooth17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth17removed {
            get {
                object obj = ResourceManager.GetObject("tooth17removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth18 {
            get {
                object obj = ResourceManager.GetObject("tooth18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth18removed {
            get {
                object obj = ResourceManager.GetObject("tooth18removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth19 {
            get {
                object obj = ResourceManager.GetObject("tooth19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth19removed {
            get {
                object obj = ResourceManager.GetObject("tooth19removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth1removed {
            get {
                object obj = ResourceManager.GetObject("tooth1removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth1removed1 {
            get {
                object obj = ResourceManager.GetObject("tooth1removed1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth2 {
            get {
                object obj = ResourceManager.GetObject("tooth2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth20 {
            get {
                object obj = ResourceManager.GetObject("tooth20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth20removed {
            get {
                object obj = ResourceManager.GetObject("tooth20removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth21 {
            get {
                object obj = ResourceManager.GetObject("tooth21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth21removed {
            get {
                object obj = ResourceManager.GetObject("tooth21removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth22 {
            get {
                object obj = ResourceManager.GetObject("tooth22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth22removed {
            get {
                object obj = ResourceManager.GetObject("tooth22removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth23 {
            get {
                object obj = ResourceManager.GetObject("tooth23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth23removed {
            get {
                object obj = ResourceManager.GetObject("tooth23removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth24 {
            get {
                object obj = ResourceManager.GetObject("tooth24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth24removed {
            get {
                object obj = ResourceManager.GetObject("tooth24removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth25 {
            get {
                object obj = ResourceManager.GetObject("tooth25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth25removed {
            get {
                object obj = ResourceManager.GetObject("tooth25removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth26 {
            get {
                object obj = ResourceManager.GetObject("tooth26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth26removed {
            get {
                object obj = ResourceManager.GetObject("tooth26removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth27 {
            get {
                object obj = ResourceManager.GetObject("tooth27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth27removed {
            get {
                object obj = ResourceManager.GetObject("tooth27removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth28 {
            get {
                object obj = ResourceManager.GetObject("tooth28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth28removed {
            get {
                object obj = ResourceManager.GetObject("tooth28removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth29 {
            get {
                object obj = ResourceManager.GetObject("tooth29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth29removed {
            get {
                object obj = ResourceManager.GetObject("tooth29removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth2removed {
            get {
                object obj = ResourceManager.GetObject("tooth2removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth3 {
            get {
                object obj = ResourceManager.GetObject("tooth3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth30 {
            get {
                object obj = ResourceManager.GetObject("tooth30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth30removed {
            get {
                object obj = ResourceManager.GetObject("tooth30removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth31 {
            get {
                object obj = ResourceManager.GetObject("tooth31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth31removed {
            get {
                object obj = ResourceManager.GetObject("tooth31removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth32 {
            get {
                object obj = ResourceManager.GetObject("tooth32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth32removed {
            get {
                object obj = ResourceManager.GetObject("tooth32removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth3removed {
            get {
                object obj = ResourceManager.GetObject("tooth3removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth4 {
            get {
                object obj = ResourceManager.GetObject("tooth4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth4removed {
            get {
                object obj = ResourceManager.GetObject("tooth4removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth5 {
            get {
                object obj = ResourceManager.GetObject("tooth5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth5removed {
            get {
                object obj = ResourceManager.GetObject("tooth5removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth6 {
            get {
                object obj = ResourceManager.GetObject("tooth6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth6removed {
            get {
                object obj = ResourceManager.GetObject("tooth6removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth7 {
            get {
                object obj = ResourceManager.GetObject("tooth7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth7removed {
            get {
                object obj = ResourceManager.GetObject("tooth7removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth8 {
            get {
                object obj = ResourceManager.GetObject("tooth8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth8removed {
            get {
                object obj = ResourceManager.GetObject("tooth8removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth9 {
            get {
                object obj = ResourceManager.GetObject("tooth9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth9removed {
            get {
                object obj = ResourceManager.GetObject("tooth9removed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopTeethRemove {
            get {
                object obj = ResourceManager.GetObject("TopTeethRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
