#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnomalousMedicalAndroid.Resource", IsApplication=true)]

namespace AnomalousMedicalAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ExpansionDownloader.Resource.Drawable.notify_panel_notification_icon_bg = global::AnomalousMedicalAndroid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::ExpansionDownloader.Resource.Id.appIcon = global::AnomalousMedicalAndroid.Resource.Id.appIcon;
			global::ExpansionDownloader.Resource.Id.description = global::AnomalousMedicalAndroid.Resource.Id.description;
			global::ExpansionDownloader.Resource.Id.notificationLayout = global::AnomalousMedicalAndroid.Resource.Id.notificationLayout;
			global::ExpansionDownloader.Resource.Id.progress_bar = global::AnomalousMedicalAndroid.Resource.Id.progress_bar;
			global::ExpansionDownloader.Resource.Id.progress_bar_frame = global::AnomalousMedicalAndroid.Resource.Id.progress_bar_frame;
			global::ExpansionDownloader.Resource.Id.progress_text = global::AnomalousMedicalAndroid.Resource.Id.progress_text;
			global::ExpansionDownloader.Resource.Id.time_remaining = global::AnomalousMedicalAndroid.Resource.Id.time_remaining;
			global::ExpansionDownloader.Resource.Id.title = global::AnomalousMedicalAndroid.Resource.Id.title;
			global::ExpansionDownloader.Resource.Layout.status_bar_ongoing_event_progress_bar = global::AnomalousMedicalAndroid.Resource.Layout.status_bar_ongoing_event_progress_bar;
			global::ExpansionDownloader.Resource.String.kilobytes_per_second = global::AnomalousMedicalAndroid.Resource.String.kilobytes_per_second;
			global::ExpansionDownloader.Resource.String.notification_download_complete = global::AnomalousMedicalAndroid.Resource.String.notification_download_complete;
			global::ExpansionDownloader.Resource.String.notification_download_failed = global::AnomalousMedicalAndroid.Resource.String.notification_download_failed;
			global::ExpansionDownloader.Resource.String.state_completed = global::AnomalousMedicalAndroid.Resource.String.state_completed;
			global::ExpansionDownloader.Resource.String.state_connecting = global::AnomalousMedicalAndroid.Resource.String.state_connecting;
			global::ExpansionDownloader.Resource.String.state_downloading = global::AnomalousMedicalAndroid.Resource.String.state_downloading;
			global::ExpansionDownloader.Resource.String.state_failed = global::AnomalousMedicalAndroid.Resource.String.state_failed;
			global::ExpansionDownloader.Resource.String.state_failed_cancelled = global::AnomalousMedicalAndroid.Resource.String.state_failed_cancelled;
			global::ExpansionDownloader.Resource.String.state_failed_fetching_url = global::AnomalousMedicalAndroid.Resource.String.state_failed_fetching_url;
			global::ExpansionDownloader.Resource.String.state_failed_sdcard_full = global::AnomalousMedicalAndroid.Resource.String.state_failed_sdcard_full;
			global::ExpansionDownloader.Resource.String.state_failed_unlicensed = global::AnomalousMedicalAndroid.Resource.String.state_failed_unlicensed;
			global::ExpansionDownloader.Resource.String.state_fetching_url = global::AnomalousMedicalAndroid.Resource.String.state_fetching_url;
			global::ExpansionDownloader.Resource.String.state_idle = global::AnomalousMedicalAndroid.Resource.String.state_idle;
			global::ExpansionDownloader.Resource.String.state_paused_by_request = global::AnomalousMedicalAndroid.Resource.String.state_paused_by_request;
			global::ExpansionDownloader.Resource.String.state_paused_network_setup_failure = global::AnomalousMedicalAndroid.Resource.String.state_paused_network_setup_failure;
			global::ExpansionDownloader.Resource.String.state_paused_network_unavailable = global::AnomalousMedicalAndroid.Resource.String.state_paused_network_unavailable;
			global::ExpansionDownloader.Resource.String.state_paused_roaming = global::AnomalousMedicalAndroid.Resource.String.state_paused_roaming;
			global::ExpansionDownloader.Resource.String.state_paused_sdcard_unavailable = global::AnomalousMedicalAndroid.Resource.String.state_paused_sdcard_unavailable;
			global::ExpansionDownloader.Resource.String.state_paused_wifi_disabled = global::AnomalousMedicalAndroid.Resource.String.state_paused_wifi_disabled;
			global::ExpansionDownloader.Resource.String.state_paused_wifi_unavailable = global::AnomalousMedicalAndroid.Resource.String.state_paused_wifi_unavailable;
			global::ExpansionDownloader.Resource.String.state_unknown = global::AnomalousMedicalAndroid.Resource.String.state_unknown;
			global::ExpansionDownloader.Resource.String.time_remaining = global::AnomalousMedicalAndroid.Resource.String.time_remaining;
			global::ExpansionDownloader.Resource.String.time_remaining_notification = global::AnomalousMedicalAndroid.Resource.String.time_remaining_notification;
			global::ExpansionDownloader.Resource.Style.ButtonBackground = global::AnomalousMedicalAndroid.Resource.Style.ButtonBackground;
			global::ExpansionDownloader.Resource.Style.NotificationText = global::AnomalousMedicalAndroid.Resource.Style.NotificationText;
			global::ExpansionDownloader.Resource.Style.NotificationTextSecondary = global::AnomalousMedicalAndroid.Resource.Style.NotificationTextSecondary;
			global::ExpansionDownloader.Resource.Style.NotificationTextShadow = global::AnomalousMedicalAndroid.Resource.Style.NotificationTextShadow;
			global::ExpansionDownloader.Resource.Style.NotificationTitle = global::AnomalousMedicalAndroid.Resource.Style.NotificationTitle;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notify_panel_notification_icon_bg = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int appIcon = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int description = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int editText1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int notificationLayout = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int progress_bar = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int progress_bar_frame = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int progress_text = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int time_remaining = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int title = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int status_bar_ongoing_event_progress_bar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040017
			public const int app_name = 2130968599;
			
			// aapt resource value: 0x7f040014
			public const int kilobytes_per_second = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int notification_download_complete = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_download_failed = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int state_completed = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int state_connecting = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int state_downloading = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int state_failed = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int state_failed_cancelled = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int state_failed_fetching_url = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int state_failed_sdcard_full = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int state_failed_unlicensed = 2130968591;
			
			// aapt resource value: 0x7f040004
			public const int state_fetching_url = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int state_idle = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int state_paused_by_request = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int state_paused_network_setup_failure = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int state_paused_network_unavailable = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int state_paused_roaming = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int state_paused_sdcard_unavailable = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int state_paused_wifi_disabled = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int state_paused_wifi_unavailable = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int state_unknown = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int time_remaining = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int time_remaining_notification = 2130968598;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050005
			public const int AnomalousMedicalTheme = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ButtonBackground = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int NotificationText = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int NotificationTextSecondary = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int NotificationTextShadow = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int NotificationTitle = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
