//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medical.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AppButton {
            get {
                object obj = ResourceManager.GetObject("AppButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap articulometricsclinic {
            get {
                object obj = ResourceManager.GetObject("articulometricsclinic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArticulometricsSplash {
            get {
                object obj = ResourceManager.GetObject("ArticulometricsSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundColorIconLarge {
            get {
                object obj = ResourceManager.GetObject("BackgroundColorIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundColorIconSmall {
            get {
                object obj = ResourceManager.GetObject("BackgroundColorIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clenchedmuscle {
            get {
                object obj = ResourceManager.GetObject("clenchedmuscle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitIcon {
            get {
                object obj = ResourceManager.GetObject("ExitIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitIconSmall {
            get {
                object obj = ResourceManager.GetObject("ExitIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FourWindowLayout {
            get {
                object obj = ResourceManager.GetObject("FourWindowLayout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HorizontalBothGroupIcon {
            get {
                object obj = ResourceManager.GetObject("HorizontalBothGroupIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HorizontalLeftGroupIcon {
            get {
                object obj = ResourceManager.GetObject("HorizontalLeftGroupIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HorizontalRightGroupIcon {
            get {
                object obj = ResourceManager.GetObject("HorizontalRightGroupIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageResolutionIconLarge {
            get {
                object obj = ResourceManager.GetObject("ImageResolutionIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageResolutionIconSmall {
            get {
                object obj = ResourceManager.GetObject("ImageResolutionIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersBottomTeethLarge {
            get {
                object obj = ResourceManager.GetObject("LayersBottomTeethLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersBottomTeethSmall {
            get {
                object obj = ResourceManager.GetObject("LayersBottomTeethSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersHyoidLarge {
            get {
                object obj = ResourceManager.GetObject("LayersHyoidLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersHyoidSmall {
            get {
                object obj = ResourceManager.GetObject("LayersHyoidSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersMandibleLarge {
            get {
                object obj = ResourceManager.GetObject("LayersMandibleLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersMandibleSmall {
            get {
                object obj = ResourceManager.GetObject("LayersMandibleSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersMuscleLarge {
            get {
                object obj = ResourceManager.GetObject("LayersMuscleLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersMuscleSmall {
            get {
                object obj = ResourceManager.GetObject("LayersMuscleSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersSkinLarge {
            get {
                object obj = ResourceManager.GetObject("LayersSkinLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersSkinSmall {
            get {
                object obj = ResourceManager.GetObject("LayersSkinSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersSkullLarge {
            get {
                object obj = ResourceManager.GetObject("LayersSkullLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersSkullSmall {
            get {
                object obj = ResourceManager.GetObject("LayersSkullSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersSpineLarge {
            get {
                object obj = ResourceManager.GetObject("LayersSpineLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersSpineSmall {
            get {
                object obj = ResourceManager.GetObject("LayersSpineSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersTMJLarge {
            get {
                object obj = ResourceManager.GetObject("LayersTMJLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersTMJSmall {
            get {
                object obj = ResourceManager.GetObject("LayersTMJSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersTopTeethLarge {
            get {
                object obj = ResourceManager.GetObject("LayersTopTeethLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayersTopTeethSmall {
            get {
                object obj = ResourceManager.GetObject("LayersTopTeethSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipHorizontalBothBack {
            get {
                object obj = ResourceManager.GetObject("ManipHorizontalBothBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipHorizontalBothForward {
            get {
                object obj = ResourceManager.GetObject("ManipHorizontalBothForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipLeftHorizontalBack {
            get {
                object obj = ResourceManager.GetObject("ManipLeftHorizontalBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipLeftHorizontalForward {
            get {
                object obj = ResourceManager.GetObject("ManipLeftHorizontalForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipResetLarge {
            get {
                object obj = ResourceManager.GetObject("ManipResetLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipResetSmall {
            get {
                object obj = ResourceManager.GetObject("ManipResetSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipRightHorizontalBack {
            get {
                object obj = ResourceManager.GetObject("ManipRightHorizontalBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipRightHorizontalForward {
            get {
                object obj = ResourceManager.GetObject("ManipRightHorizontalForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipVerticalClosed {
            get {
                object obj = ResourceManager.GetObject("ManipVerticalClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManipVerticalOpen {
            get {
                object obj = ResourceManager.GetObject("ManipVerticalOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MRIWizardLarge {
            get {
                object obj = ResourceManager.GetObject("MRIWizardLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MRIWizardSmall {
            get {
                object obj = ResourceManager.GetObject("MRIWizardSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavIconLarge {
            get {
                object obj = ResourceManager.GetObject("NavIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavIconSmall {
            get {
                object obj = ResourceManager.GetObject("NavIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap neutralmuscle {
            get {
                object obj = ResourceManager.GetObject("neutralmuscle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OneWindowLayout {
            get {
                object obj = ResourceManager.GetObject("OneWindowLayout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenIconLarge {
            get {
                object obj = ResourceManager.GetObject("OpenIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenIconSmall {
            get {
                object obj = ResourceManager.GetObject("OpenIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpeningGroupIcon {
            get {
                object obj = ResourceManager.GetObject("OpeningGroupIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openmuscle {
            get {
                object obj = ResourceManager.GetObject("openmuscle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsIconLarge {
            get {
                object obj = ResourceManager.GetObject("OptionsIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsIconSmall {
            get {
                object obj = ResourceManager.GetObject("OptionsIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlaybackButtons {
            get {
                object obj = ResourceManager.GetObject("PlaybackButtons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RenderIconLarge {
            get {
                object obj = ResourceManager.GetObject("RenderIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RenderIconSmall {
            get {
                object obj = ResourceManager.GetObject("RenderIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveLarge {
            get {
                object obj = ResourceManager.GetObject("SaveLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveSmall {
            get {
                object obj = ResourceManager.GetObject("SaveSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SceneSelectLarge {
            get {
                object obj = ResourceManager.GetObject("SceneSelectLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SequenceIconLarge {
            get {
                object obj = ResourceManager.GetObject("SequenceIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SequenceIconSmall {
            get {
                object obj = ResourceManager.GetObject("SequenceIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatsIconLarge {
            get {
                object obj = ResourceManager.GetObject("StatsIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatsIconSmall {
            get {
                object obj = ResourceManager.GetObject("StatsIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TeethCollisionIconLarge {
            get {
                object obj = ResourceManager.GetObject("TeethCollisionIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TeethCollisionIconSmall {
            get {
                object obj = ResourceManager.GetObject("TeethCollisionIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThreeWindowLayout {
            get {
                object obj = ResourceManager.GetObject("ThreeWindowLayout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TwoWindowLayout {
            get {
                object obj = ResourceManager.GetObject("TwoWindowLayout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WindowLayoutIconLarge {
            get {
                object obj = ResourceManager.GetObject("WindowLayoutIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WindowLayoutIconSmall {
            get {
                object obj = ResourceManager.GetObject("WindowLayoutIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
