//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medical.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap clenchedmuscle {
            get {
                object obj = ResourceManager.GetObject("clenchedmuscle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDegenerationExtreme {
            get {
                object obj = ResourceManager.GetObject("LeftDegenerationExtreme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDegenerationMild {
            get {
                object obj = ResourceManager.GetObject("LeftDegenerationMild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDegenerationModerate {
            get {
                object obj = ResourceManager.GetObject("LeftDegenerationModerate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDegenerationNormal {
            get {
                object obj = ResourceManager.GetObject("LeftDegenerationNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDegenerationSevere {
            get {
                object obj = ResourceManager.GetObject("LeftDegenerationSevere", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthExtremeTotalMandible1 {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthExtremeTotalMandible1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthExtremeTotalMandible2 {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthExtremeTotalMandible2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthExtremeTotalMandible3 {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthExtremeTotalMandible3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthMildCompensation {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthMildCompensation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthMildNoCompensation1 {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthMildNoCompensation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthMildNoCompensation2 {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthMildNoCompensation2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthMildNoCompensation3 {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthMildNoCompensation3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthModerateCompensation1 {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthModerateCompensation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthModerateCompensation2 {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthModerateCompensation2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthModerateCompensation3 {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthModerateCompensation3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthModerateNoCompensation {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthModerateNoCompensation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftGrowthNormal {
            get {
                object obj = ResourceManager.GetObject("LeftGrowthNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap neutralmuscle {
            get {
                object obj = ResourceManager.GetObject("neutralmuscle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openmuscle {
            get {
                object obj = ResourceManager.GetObject("openmuscle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDegenerationExtreme {
            get {
                object obj = ResourceManager.GetObject("RightDegenerationExtreme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDegenerationMild {
            get {
                object obj = ResourceManager.GetObject("RightDegenerationMild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDegenerationModerate {
            get {
                object obj = ResourceManager.GetObject("RightDegenerationModerate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDegenerationNormal {
            get {
                object obj = ResourceManager.GetObject("RightDegenerationNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDegenerationSevere {
            get {
                object obj = ResourceManager.GetObject("RightDegenerationSevere", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthExtremeTotalMandible1 {
            get {
                object obj = ResourceManager.GetObject("RightGrowthExtremeTotalMandible1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthExtremeTotalMandible2 {
            get {
                object obj = ResourceManager.GetObject("RightGrowthExtremeTotalMandible2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthExtremeTotalMandible3 {
            get {
                object obj = ResourceManager.GetObject("RightGrowthExtremeTotalMandible3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthMildCompensation {
            get {
                object obj = ResourceManager.GetObject("RightGrowthMildCompensation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthMildNoCompensation1 {
            get {
                object obj = ResourceManager.GetObject("RightGrowthMildNoCompensation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthMildNoCompensation2 {
            get {
                object obj = ResourceManager.GetObject("RightGrowthMildNoCompensation2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthMildNoCompensation3 {
            get {
                object obj = ResourceManager.GetObject("RightGrowthMildNoCompensation3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthModerateCompensation1 {
            get {
                object obj = ResourceManager.GetObject("RightGrowthModerateCompensation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthModerateCompensation2 {
            get {
                object obj = ResourceManager.GetObject("RightGrowthModerateCompensation2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthModerateCompensation3 {
            get {
                object obj = ResourceManager.GetObject("RightGrowthModerateCompensation3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthModerateNoCompensation {
            get {
                object obj = ResourceManager.GetObject("RightGrowthModerateNoCompensation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightGrowthNormal {
            get {
                object obj = ResourceManager.GetObject("RightGrowthNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
