//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medical.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AddStateLarge {
            get {
                object obj = ResourceManager.GetObject("AddStateLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddStateSmall {
            get {
                object obj = ResourceManager.GetObject("AddStateSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap articulometricsresearch {
            get {
                object obj = ResourceManager.GetObject("articulometricsresearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundColorIconLarge {
            get {
                object obj = ResourceManager.GetObject("BackgroundColorIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundColorIconSmall {
            get {
                object obj = ResourceManager.GetObject("BackgroundColorIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clenchedmuscle {
            get {
                object obj = ResourceManager.GetObject("clenchedmuscle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloneWindowLarge {
            get {
                object obj = ResourceManager.GetObject("CloneWindowLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloneWindowSmall {
            get {
                object obj = ResourceManager.GetObject("CloneWindowSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disc {
            get {
                object obj = ResourceManager.GetObject("disc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap extremeLeftSide {
            get {
                object obj = ResourceManager.GetObject("extremeLeftSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap extremeRightSide {
            get {
                object obj = ResourceManager.GetObject("extremeRightSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap leftcondyleresize {
            get {
                object obj = ResourceManager.GetObject("leftcondyleresize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mandibletranslation {
            get {
                object obj = ResourceManager.GetObject("mandibletranslation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap middleLeftSide {
            get {
                object obj = ResourceManager.GetObject("middleLeftSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap middleRightSide {
            get {
                object obj = ResourceManager.GetObject("middleRightSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap neutralmuscle {
            get {
                object obj = ResourceManager.GetObject("neutralmuscle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewSequenceLarge {
            get {
                object obj = ResourceManager.GetObject("NewSequenceLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewSequenceSmall {
            get {
                object obj = ResourceManager.GetObject("NewSequenceSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewStatesLarge {
            get {
                object obj = ResourceManager.GetObject("NewStatesLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewStatesSmall {
            get {
                object obj = ResourceManager.GetObject("NewStatesSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap normalLeftSide {
            get {
                object obj = ResourceManager.GetObject("normalLeftSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap normalRightSide {
            get {
                object obj = ResourceManager.GetObject("normalRightSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openmuscle {
            get {
                object obj = ResourceManager.GetObject("openmuscle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenSequenceLarge {
            get {
                object obj = ResourceManager.GetObject("OpenSequenceLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenSequenceSmall {
            get {
                object obj = ResourceManager.GetObject("OpenSequenceSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenStatesLarge {
            get {
                object obj = ResourceManager.GetObject("OpenStatesLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenStatesSmall {
            get {
                object obj = ResourceManager.GetObject("OpenStatesSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsIconLarge {
            get {
                object obj = ResourceManager.GetObject("OptionsIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsIconSmall {
            get {
                object obj = ResourceManager.GetObject("OptionsIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightcondyleresize {
            get {
                object obj = ResourceManager.GetObject("rightcondyleresize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveSequenceLarge {
            get {
                object obj = ResourceManager.GetObject("SaveSequenceLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveSequenceSmall {
            get {
                object obj = ResourceManager.GetObject("SaveSequenceSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveStatesLarge {
            get {
                object obj = ResourceManager.GetObject("SaveStatesLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveStatesSmall {
            get {
                object obj = ResourceManager.GetObject("SaveStatesSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SequenceIconSmall {
            get {
                object obj = ResourceManager.GetObject("SequenceIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StateButtons {
            get {
                object obj = ResourceManager.GetObject("StateButtons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatsIconLarge {
            get {
                object obj = ResourceManager.GetObject("StatsIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth1 {
            get {
                object obj = ResourceManager.GetObject("tooth1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth10 {
            get {
                object obj = ResourceManager.GetObject("tooth10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth11 {
            get {
                object obj = ResourceManager.GetObject("tooth11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth12 {
            get {
                object obj = ResourceManager.GetObject("tooth12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth13 {
            get {
                object obj = ResourceManager.GetObject("tooth13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth14 {
            get {
                object obj = ResourceManager.GetObject("tooth14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth15 {
            get {
                object obj = ResourceManager.GetObject("tooth15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth16 {
            get {
                object obj = ResourceManager.GetObject("tooth16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth17 {
            get {
                object obj = ResourceManager.GetObject("tooth17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth18 {
            get {
                object obj = ResourceManager.GetObject("tooth18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth19 {
            get {
                object obj = ResourceManager.GetObject("tooth19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth2 {
            get {
                object obj = ResourceManager.GetObject("tooth2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth20 {
            get {
                object obj = ResourceManager.GetObject("tooth20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth21 {
            get {
                object obj = ResourceManager.GetObject("tooth21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth22 {
            get {
                object obj = ResourceManager.GetObject("tooth22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth23 {
            get {
                object obj = ResourceManager.GetObject("tooth23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth24 {
            get {
                object obj = ResourceManager.GetObject("tooth24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth25 {
            get {
                object obj = ResourceManager.GetObject("tooth25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth26 {
            get {
                object obj = ResourceManager.GetObject("tooth26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth27 {
            get {
                object obj = ResourceManager.GetObject("tooth27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth28 {
            get {
                object obj = ResourceManager.GetObject("tooth28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth29 {
            get {
                object obj = ResourceManager.GetObject("tooth29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth3 {
            get {
                object obj = ResourceManager.GetObject("tooth3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth30 {
            get {
                object obj = ResourceManager.GetObject("tooth30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth31 {
            get {
                object obj = ResourceManager.GetObject("tooth31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth32 {
            get {
                object obj = ResourceManager.GetObject("tooth32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth4 {
            get {
                object obj = ResourceManager.GetObject("tooth4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth5 {
            get {
                object obj = ResourceManager.GetObject("tooth5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth6 {
            get {
                object obj = ResourceManager.GetObject("tooth6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth7 {
            get {
                object obj = ResourceManager.GetObject("tooth7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth8 {
            get {
                object obj = ResourceManager.GetObject("tooth8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tooth9 {
            get {
                object obj = ResourceManager.GetObject("tooth9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WindowLayoutIconLarge {
            get {
                object obj = ResourceManager.GetObject("WindowLayoutIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WindowLayoutIconSmall {
            get {
                object obj = ResourceManager.GetObject("WindowLayoutIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
