namespace Medical
{

public enum class Features : int
{
	PIPER_JBO_LITE = 155,
	PIPER_JBO_STANDARD = 156,
	PIPER_JBO_GRAPHICS = 157,
	WIZARD_DOPPLER = 158,
	WIZARD_TEETH = 159,
	WIZARD_PROFILE = 160,
	WIZARD_BONE = 161,
	WIZARD_DISC = 162,
	WIZARD_PROFILE_TEETH = 163,
	WIZARD_DOPPLER_PROFILE_TEETH = 164,
	WIZARD_DOPPLER_BONE_TEETH = 165,
	WIZARD_DISC_BONE_TEETH = 166,
};

}