namespace Medical
{

public enum class Features : int
{
	ANOMALOUS_MEDICAL_KEY = 0,
	PIPER_JBO_MODULE = 1,
	PIPER_JBO_WIZARD_DOPPLER = 2,
	PIPER_JBO_WIZARD_DENTITION = 3,
	PIPER_JBO_WIZARD_CEPHALOMETRIC = 4,
	PIPER_JBO_WIZARD_MANDIBLE = 5,
	PIPER_JBO_WIZARD_DISC = 6,
	PIPER_JBO_WIZARD_CEPHALOMETRIC_DENTITION = 7,
	PIPER_JBO_WIZARD_CLINICAL_DOPPLER = 8,
	PIPER_JBO_WIZARD_RADIOGRAPHY = 9,
	PIPER_JBO_WIZARD_MRI = 10,
	PIPER_JBO_VERSION_DOPPLER = 11,
	PIPER_JBO_VERSION_DENTITION_PROFILE = 12,
	PIPER_JBO_VERSION_CLINICAL = 13,
	PIPER_JBO_VERSION_RADIOGRAPHY_CT = 14,
	PIPER_JBO_VERSION_MRI = 15,
	PIPER_JBO_VERSION_GRAPHICS = 16,
	PIPER_JBO_FEATURE_CUSTOM_LAYERS = 17,
	PIPER_JBO_FEATURE_FULL_RENDERING = 18,
	PIPER_JBO_FEATURE_CLONE_WINDOW = 19,
	PIPER_JBO_FEATURE_SIMULATION = 20,
};

}