namespace Medical
{

public enum class Features : int
{
	PIPER_JBO_LITE = 155,
	PIPER_JBO_STANDARD = 156,
	PIPER_JBO_GRAPHICS = 157,
	WIZARD_PIPER_JBO_DOPPLER = 158,
	WIZARD_PIPER_JBO_TEETH = 159,
	WIZARD_PIPER_JBO_PROFILE = 160,
	WIZARD_PIPER_JBO_BONE = 161,
	WIZARD_PIPER_JBO_DISC = 162,
	WIZARD_PIPER_JBO_PROFILE_TEETH = 163,
	WIZARD_PIPER_JBO_CT = 164,
	WIZARD_PIPER_JBO_CLINICAL = 165,
	WIZARD_PIPER_JBO_MRI = 166,
};

}