<Save>
  <Saveable type="Medical.CameraPosition, Standalone" id="3">
    <Vector3 name="Translation">0, -49.8942, 8.067075</Vector3>
    <Vector3 name="LookAt">0, -10.03267, 8.027217</Vector3>
  </Saveable>
  <Saveable type="Medical.CameraPosition, Standalone" id="4">
    <Vector3 name="Translation">0, 29.82872, 8.205588</Vector3>
    <Vector3 name="LookAt">0, -10.03281, 8.16573</Vector3>
  </Saveable>
  <Saveable type="Medical.CameraPosition, Standalone" id="5">
    <Vector3 name="Translation">-39.8133, -10.03284, 5.89741</Vector3>
    <Vector3 name="LookAt">0, -10.03284, 7.857922</Vector3>
  </Saveable>
  <Saveable type="Medical.CameraPosition, Standalone" id="6">
    <Vector3 name="Translation">39.81329, -10.03284, 5.89741</Vector3>
    <Vector3 name="LookAt">0, -10.03284, 7.857922</Vector3>
  </Saveable>
  <Saveable type="Medical.CameraPosition, Standalone" id="7">
    <Vector3 name="Translation">0, -10.03284, 47.71947</Vector3>
    <Vector3 name="LookAt">0, -10.03284, 7.857922</Vector3>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="9">
    <String name="TransparencyObject">Airway</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="10">
    <String name="TransparencyObject">Nasal Cartilage</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="11">
    <String name="TransparencyObject">Nasal Cavity</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="12">
    <String name="TransparencyObject">Pharynx</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="13">
    <String name="TransparencyObject">Septal Cartilage</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="14">
    <String name="TransparencyObject">Hyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="15">
    <String name="TransparencyObject">Left Eminence</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="16">
    <String name="TransparencyObject">Mandible</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="17">
    <String name="TransparencyObject">Maxillary Sinus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="18">
    <String name="TransparencyObject">Right Eminence</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="19">
    <String name="TransparencyObject">Skull</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="20">
    <String name="TransparencyObject">Skull Interior</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="21">
    <String name="TransparencyObject">LeftParotidGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="22">
    <String name="TransparencyObject">LeftSubmandibularSublingualGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="23">
    <String name="TransparencyObject">Lips</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="24">
    <String name="TransparencyObject">Mandible Gums</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="25">
    <String name="TransparencyObject">Maxilla Gums</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="26">
    <String name="TransparencyObject">RightParotidGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="27">
    <String name="TransparencyObject">RightSubmandibularSublingualGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="28">
    <String name="TransparencyObject">Tongue</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="29">
    <String name="TransparencyObject">Uvula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="30">
    <String name="TransparencyObject">Digastric Belly</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="31">
    <String name="TransparencyObject">Geniohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="32">
    <String name="TransparencyObject">Left Digastric</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="33">
    <String name="TransparencyObject">Left Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="34">
    <String name="TransparencyObject">Left Lateral Superior Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="35">
    <String name="TransparencyObject">Left Masseter</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="36">
    <String name="TransparencyObject">Left Medial Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="37">
    <String name="TransparencyObject">Left Stylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="38">
    <String name="TransparencyObject">Left Temporalis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="39">
    <String name="TransparencyObject">Mylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="40">
    <String name="TransparencyObject">Omohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="41">
    <String name="TransparencyObject">Right Digastric</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="42">
    <String name="TransparencyObject">Right Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="43">
    <String name="TransparencyObject">Right Masseter</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="44">
    <String name="TransparencyObject">Right Medial Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="45">
    <String name="TransparencyObject">Right Stylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="46">
    <String name="TransparencyObject">Right Superior Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="47">
    <String name="TransparencyObject">Right Temporalis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="48">
    <String name="TransparencyObject">Sternohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="49">
    <String name="TransparencyObject">Sternothyroid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="50">
    <String name="TransparencyObject">Thyrohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="51">
    <String name="TransparencyObject">Thyroid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="52">
    <String name="TransparencyObject">Head Arteries</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="53">
    <String name="TransparencyObject">Head Lymph Nodes</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="54">
    <String name="TransparencyObject">Head Veins</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="55">
    <String name="TransparencyObject">Left Auriculo Temporal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="56">
    <String name="TransparencyObject">Left Buccal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="57">
    <String name="TransparencyObject">Left Greater Auricular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="58">
    <String name="TransparencyObject">Left Greater Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="59">
    <String name="TransparencyObject">Left Infraorbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="60">
    <String name="TransparencyObject">Left Lesser Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="61">
    <String name="TransparencyObject">Left Lingual Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="62">
    <String name="TransparencyObject">Left Mandibular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="63">
    <String name="TransparencyObject">Left Supra Orbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="64">
    <String name="TransparencyObject">Left Trigeminal Ganglion</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="65">
    <String name="TransparencyObject">Right Auriculo Temporal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="66">
    <String name="TransparencyObject">Right Buccal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="67">
    <String name="TransparencyObject">Right Greater Auricular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="68">
    <String name="TransparencyObject">Right Greater Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="69">
    <String name="TransparencyObject">Right Infraorbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="70">
    <String name="TransparencyObject">Right Lesser Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="71">
    <String name="TransparencyObject">Right Lingual Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="72">
    <String name="TransparencyObject">Right Mandibular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="73">
    <String name="TransparencyObject">Right Supra Orbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="74">
    <String name="TransparencyObject">Right Trigeminal Ganglion</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="75">
    <String name="TransparencyObject">Brain</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="76">
    <String name="TransparencyObject">BrainStemMadulaPons</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="77">
    <String name="TransparencyObject">Cerebellum</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="78">
    <String name="TransparencyObject">Chest Manubrium Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="79">
    <String name="TransparencyObject">Clavical</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="80">
    <String name="TransparencyObject">FalxCerebri</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="81">
    <String name="TransparencyObject">FirstRib</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="82">
    <String name="TransparencyObject">Fornix</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="83">
    <String name="TransparencyObject">Hypothalamus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="84">
    <String name="TransparencyObject">LateralGlobusPallidus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="85">
    <String name="TransparencyObject">Left Conoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="86">
    <String name="TransparencyObject">Left Coraco Acromial Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="87">
    <String name="TransparencyObject">Left Infraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="88">
    <String name="TransparencyObject">Left Subscapularis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="89">
    <String name="TransparencyObject">Left Superior Acromio Clavicular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="90">
    <String name="TransparencyObject">Left Superior Transverse Scapular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="91">
    <String name="TransparencyObject">Left Supraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="92">
    <String name="TransparencyObject">Left Teres Major</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="93">
    <String name="TransparencyObject">Left Teres Minor</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="94">
    <String name="TransparencyObject">Left Trapezoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="95">
    <String name="TransparencyObject">LeftScapula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="96">
    <String name="TransparencyObject">Manubrium</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="97">
    <String name="TransparencyObject">MedialGlobusPallidus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="98">
    <String name="TransparencyObject">OpticCanal</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="99">
    <String name="TransparencyObject">PinealGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="100">
    <String name="TransparencyObject">PituitaryGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="101">
    <String name="TransparencyObject">Putamen</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="102">
    <String name="TransparencyObject">Right Conoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="103">
    <String name="TransparencyObject">Right Coraco Acromial Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="104">
    <String name="TransparencyObject">Right Infraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="105">
    <String name="TransparencyObject">Right Subscapularis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="106">
    <String name="TransparencyObject">Right Superior Acromio Clavicular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="107">
    <String name="TransparencyObject">Right Supraspinatous</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="108">
    <String name="TransparencyObject">Right Teres Major</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="109">
    <String name="TransparencyObject">Right Teres Minor</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="110">
    <String name="TransparencyObject">RightScapula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="111">
    <String name="TransparencyObject">Spinal Nerves</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="112">
    <String name="TransparencyObject">Sternocleidomastoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="113">
    <String name="TransparencyObject">SubstantiaNigra</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="114">
    <String name="TransparencyObject">SubthalamicNucleus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="115">
    <String name="TransparencyObject">Thalamus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="116">
    <String name="TransparencyObject">Trapezius</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="117">
    <String name="TransparencyObject">Trapezoid Ligament Left</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="118">
    <String name="TransparencyObject">Trapezoid Ligament Right</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="119">
    <String name="TransparencyObject">Ventricles</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="120">
    <String name="TransparencyObject">Eyebrows and Eyelashes</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="121">
    <String name="TransparencyObject">Left Eye</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="122">
    <String name="TransparencyObject">Right Eye</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="123">
    <String name="TransparencyObject">Skin</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="124">
    <String name="TransparencyObject">Alar Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="125">
    <String name="TransparencyObject">Anterior Atlanto Occip Membrane</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="126">
    <String name="TransparencyObject">Anterior Longitude Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="127">
    <String name="TransparencyObject">Apical Ligament Of Dens</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="128">
    <String name="TransparencyObject">Atlanto Occipital Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="129">
    <String name="TransparencyObject">Atlantoaxial Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="130">
    <String name="TransparencyObject">C1</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="131">
    <String name="TransparencyObject">C2</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="132">
    <String name="TransparencyObject">C3</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="133">
    <String name="TransparencyObject">C4</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="134">
    <String name="TransparencyObject">C5</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="135">
    <String name="TransparencyObject">C6</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="136">
    <String name="TransparencyObject">C7</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="137">
    <String name="TransparencyObject">Intertransverse Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="138">
    <String name="TransparencyObject">Intervertebral Disc Capsules</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="139">
    <String name="TransparencyObject">Ligamenta Flava</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="140">
    <String name="TransparencyObject">Nuchal Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="141">
    <String name="TransparencyObject">Posterior Atlanto Occip Memb</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="142">
    <String name="TransparencyObject">Posterior Longitude Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="143">
    <String name="TransparencyObject">T1</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="144">
    <String name="TransparencyObject">Tectorial Membrane</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="145">
    <String name="TransparencyObject">Transverse Ligament Of Atlas</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="146">
    <String name="TransparencyObject">VDiscC2C3</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="147">
    <String name="TransparencyObject">VDiscC3C4</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="148">
    <String name="TransparencyObject">VDiscC4C5</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="149">
    <String name="TransparencyObject">VDiscC5C6</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="150">
    <String name="TransparencyObject">VDiscC6C7</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="151">
    <String name="TransparencyObject">Zygapophysial Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="152">
    <String name="TransparencyObject">Tooth 1</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="153">
    <String name="TransparencyObject">Tooth 2</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="154">
    <String name="TransparencyObject">Tooth 3</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="155">
    <String name="TransparencyObject">Tooth 4</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="156">
    <String name="TransparencyObject">Tooth 5</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="157">
    <String name="TransparencyObject">Tooth 6</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="158">
    <String name="TransparencyObject">Tooth 7</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="159">
    <String name="TransparencyObject">Tooth 8</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="160">
    <String name="TransparencyObject">Tooth 9</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="161">
    <String name="TransparencyObject">Tooth 10</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="162">
    <String name="TransparencyObject">Tooth 11</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="163">
    <String name="TransparencyObject">Tooth 12</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="164">
    <String name="TransparencyObject">Tooth 13</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="165">
    <String name="TransparencyObject">Tooth 14</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="166">
    <String name="TransparencyObject">Tooth 15</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="167">
    <String name="TransparencyObject">Tooth 16</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="168">
    <String name="TransparencyObject">Tooth 17</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="169">
    <String name="TransparencyObject">Tooth 18</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="170">
    <String name="TransparencyObject">Tooth 19</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="171">
    <String name="TransparencyObject">Tooth 20</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="172">
    <String name="TransparencyObject">Tooth 21</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="173">
    <String name="TransparencyObject">Tooth 22</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="174">
    <String name="TransparencyObject">Tooth 23</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="175">
    <String name="TransparencyObject">Tooth 24</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="176">
    <String name="TransparencyObject">Tooth 25</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="177">
    <String name="TransparencyObject">Tooth 26</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="178">
    <String name="TransparencyObject">Tooth 27</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="179">
    <String name="TransparencyObject">Tooth 28</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="180">
    <String name="TransparencyObject">Tooth 29</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="181">
    <String name="TransparencyObject">Tooth 30</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="182">
    <String name="TransparencyObject">Tooth 31</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="183">
    <String name="TransparencyObject">Tooth 32</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="184">
    <String name="TransparencyObject">Left TMJ Disc</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="185">
    <String name="TransparencyObject">Right TMJ Disc</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.EditableLayerState, Standalone" id="8">
    <String name="Name">AllTeethLayers</String>
    <Saveable name="Entry0" id="9" />
    <Saveable name="Entry1" id="10" />
    <Saveable name="Entry2" id="11" />
    <Saveable name="Entry3" id="12" />
    <Saveable name="Entry4" id="13" />
    <Saveable name="Entry5" id="14" />
    <Saveable name="Entry6" id="15" />
    <Saveable name="Entry7" id="16" />
    <Saveable name="Entry8" id="17" />
    <Saveable name="Entry9" id="18" />
    <Saveable name="Entry10" id="19" />
    <Saveable name="Entry11" id="20" />
    <Saveable name="Entry12" id="21" />
    <Saveable name="Entry13" id="22" />
    <Saveable name="Entry14" id="23" />
    <Saveable name="Entry15" id="24" />
    <Saveable name="Entry16" id="25" />
    <Saveable name="Entry17" id="26" />
    <Saveable name="Entry18" id="27" />
    <Saveable name="Entry19" id="28" />
    <Saveable name="Entry20" id="29" />
    <Saveable name="Entry21" id="30" />
    <Saveable name="Entry22" id="31" />
    <Saveable name="Entry23" id="32" />
    <Saveable name="Entry24" id="33" />
    <Saveable name="Entry25" id="34" />
    <Saveable name="Entry26" id="35" />
    <Saveable name="Entry27" id="36" />
    <Saveable name="Entry28" id="37" />
    <Saveable name="Entry29" id="38" />
    <Saveable name="Entry30" id="39" />
    <Saveable name="Entry31" id="40" />
    <Saveable name="Entry32" id="41" />
    <Saveable name="Entry33" id="42" />
    <Saveable name="Entry34" id="43" />
    <Saveable name="Entry35" id="44" />
    <Saveable name="Entry36" id="45" />
    <Saveable name="Entry37" id="46" />
    <Saveable name="Entry38" id="47" />
    <Saveable name="Entry39" id="48" />
    <Saveable name="Entry40" id="49" />
    <Saveable name="Entry41" id="50" />
    <Saveable name="Entry42" id="51" />
    <Saveable name="Entry43" id="52" />
    <Saveable name="Entry44" id="53" />
    <Saveable name="Entry45" id="54" />
    <Saveable name="Entry46" id="55" />
    <Saveable name="Entry47" id="56" />
    <Saveable name="Entry48" id="57" />
    <Saveable name="Entry49" id="58" />
    <Saveable name="Entry50" id="59" />
    <Saveable name="Entry51" id="60" />
    <Saveable name="Entry52" id="61" />
    <Saveable name="Entry53" id="62" />
    <Saveable name="Entry54" id="63" />
    <Saveable name="Entry55" id="64" />
    <Saveable name="Entry56" id="65" />
    <Saveable name="Entry57" id="66" />
    <Saveable name="Entry58" id="67" />
    <Saveable name="Entry59" id="68" />
    <Saveable name="Entry60" id="69" />
    <Saveable name="Entry61" id="70" />
    <Saveable name="Entry62" id="71" />
    <Saveable name="Entry63" id="72" />
    <Saveable name="Entry64" id="73" />
    <Saveable name="Entry65" id="74" />
    <Saveable name="Entry66" id="75" />
    <Saveable name="Entry67" id="76" />
    <Saveable name="Entry68" id="77" />
    <Saveable name="Entry69" id="78" />
    <Saveable name="Entry70" id="79" />
    <Saveable name="Entry71" id="80" />
    <Saveable name="Entry72" id="81" />
    <Saveable name="Entry73" id="82" />
    <Saveable name="Entry74" id="83" />
    <Saveable name="Entry75" id="84" />
    <Saveable name="Entry76" id="85" />
    <Saveable name="Entry77" id="86" />
    <Saveable name="Entry78" id="87" />
    <Saveable name="Entry79" id="88" />
    <Saveable name="Entry80" id="89" />
    <Saveable name="Entry81" id="90" />
    <Saveable name="Entry82" id="91" />
    <Saveable name="Entry83" id="92" />
    <Saveable name="Entry84" id="93" />
    <Saveable name="Entry85" id="94" />
    <Saveable name="Entry86" id="95" />
    <Saveable name="Entry87" id="96" />
    <Saveable name="Entry88" id="97" />
    <Saveable name="Entry89" id="98" />
    <Saveable name="Entry90" id="99" />
    <Saveable name="Entry91" id="100" />
    <Saveable name="Entry92" id="101" />
    <Saveable name="Entry93" id="102" />
    <Saveable name="Entry94" id="103" />
    <Saveable name="Entry95" id="104" />
    <Saveable name="Entry96" id="105" />
    <Saveable name="Entry97" id="106" />
    <Saveable name="Entry98" id="107" />
    <Saveable name="Entry99" id="108" />
    <Saveable name="Entry100" id="109" />
    <Saveable name="Entry101" id="110" />
    <Saveable name="Entry102" id="111" />
    <Saveable name="Entry103" id="112" />
    <Saveable name="Entry104" id="113" />
    <Saveable name="Entry105" id="114" />
    <Saveable name="Entry106" id="115" />
    <Saveable name="Entry107" id="116" />
    <Saveable name="Entry108" id="117" />
    <Saveable name="Entry109" id="118" />
    <Saveable name="Entry110" id="119" />
    <Saveable name="Entry111" id="120" />
    <Saveable name="Entry112" id="121" />
    <Saveable name="Entry113" id="122" />
    <Saveable name="Entry114" id="123" />
    <Saveable name="Entry115" id="124" />
    <Saveable name="Entry116" id="125" />
    <Saveable name="Entry117" id="126" />
    <Saveable name="Entry118" id="127" />
    <Saveable name="Entry119" id="128" />
    <Saveable name="Entry120" id="129" />
    <Saveable name="Entry121" id="130" />
    <Saveable name="Entry122" id="131" />
    <Saveable name="Entry123" id="132" />
    <Saveable name="Entry124" id="133" />
    <Saveable name="Entry125" id="134" />
    <Saveable name="Entry126" id="135" />
    <Saveable name="Entry127" id="136" />
    <Saveable name="Entry128" id="137" />
    <Saveable name="Entry129" id="138" />
    <Saveable name="Entry130" id="139" />
    <Saveable name="Entry131" id="140" />
    <Saveable name="Entry132" id="141" />
    <Saveable name="Entry133" id="142" />
    <Saveable name="Entry134" id="143" />
    <Saveable name="Entry135" id="144" />
    <Saveable name="Entry136" id="145" />
    <Saveable name="Entry137" id="146" />
    <Saveable name="Entry138" id="147" />
    <Saveable name="Entry139" id="148" />
    <Saveable name="Entry140" id="149" />
    <Saveable name="Entry141" id="150" />
    <Saveable name="Entry142" id="151" />
    <Saveable name="Entry143" id="152" />
    <Saveable name="Entry144" id="153" />
    <Saveable name="Entry145" id="154" />
    <Saveable name="Entry146" id="155" />
    <Saveable name="Entry147" id="156" />
    <Saveable name="Entry148" id="157" />
    <Saveable name="Entry149" id="158" />
    <Saveable name="Entry150" id="159" />
    <Saveable name="Entry151" id="160" />
    <Saveable name="Entry152" id="161" />
    <Saveable name="Entry153" id="162" />
    <Saveable name="Entry154" id="163" />
    <Saveable name="Entry155" id="164" />
    <Saveable name="Entry156" id="165" />
    <Saveable name="Entry157" id="166" />
    <Saveable name="Entry158" id="167" />
    <Saveable name="Entry159" id="168" />
    <Saveable name="Entry160" id="169" />
    <Saveable name="Entry161" id="170" />
    <Saveable name="Entry162" id="171" />
    <Saveable name="Entry163" id="172" />
    <Saveable name="Entry164" id="173" />
    <Saveable name="Entry165" id="174" />
    <Saveable name="Entry166" id="175" />
    <Saveable name="Entry167" id="176" />
    <Saveable name="Entry168" id="177" />
    <Saveable name="Entry169" id="178" />
    <Saveable name="Entry170" id="179" />
    <Saveable name="Entry171" id="180" />
    <Saveable name="Entry172" id="181" />
    <Saveable name="Entry173" id="182" />
    <Saveable name="Entry174" id="183" />
    <Saveable name="Entry175" id="184" />
    <Saveable name="Entry176" id="185" />
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="187">
    <String name="TransparencyObject">Airway</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="188">
    <String name="TransparencyObject">Nasal Cartilage</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="189">
    <String name="TransparencyObject">Nasal Cavity</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="190">
    <String name="TransparencyObject">Pharynx</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="191">
    <String name="TransparencyObject">Septal Cartilage</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="192">
    <String name="TransparencyObject">Hyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="193">
    <String name="TransparencyObject">Left Eminence</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="194">
    <String name="TransparencyObject">Mandible</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="195">
    <String name="TransparencyObject">Maxillary Sinus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="196">
    <String name="TransparencyObject">Right Eminence</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="197">
    <String name="TransparencyObject">Skull</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="198">
    <String name="TransparencyObject">Skull Interior</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="199">
    <String name="TransparencyObject">LeftParotidGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="200">
    <String name="TransparencyObject">LeftSubmandibularSublingualGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="201">
    <String name="TransparencyObject">Lips</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="202">
    <String name="TransparencyObject">Mandible Gums</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="203">
    <String name="TransparencyObject">Maxilla Gums</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="204">
    <String name="TransparencyObject">RightParotidGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="205">
    <String name="TransparencyObject">RightSubmandibularSublingualGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="206">
    <String name="TransparencyObject">Tongue</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="207">
    <String name="TransparencyObject">Uvula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="208">
    <String name="TransparencyObject">Digastric Belly</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="209">
    <String name="TransparencyObject">Geniohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="210">
    <String name="TransparencyObject">Left Digastric</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="211">
    <String name="TransparencyObject">Left Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="212">
    <String name="TransparencyObject">Left Lateral Superior Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="213">
    <String name="TransparencyObject">Left Masseter</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="214">
    <String name="TransparencyObject">Left Medial Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="215">
    <String name="TransparencyObject">Left Stylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="216">
    <String name="TransparencyObject">Left Temporalis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="217">
    <String name="TransparencyObject">Mylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="218">
    <String name="TransparencyObject">Omohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="219">
    <String name="TransparencyObject">Right Digastric</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="220">
    <String name="TransparencyObject">Right Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="221">
    <String name="TransparencyObject">Right Masseter</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="222">
    <String name="TransparencyObject">Right Medial Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="223">
    <String name="TransparencyObject">Right Stylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="224">
    <String name="TransparencyObject">Right Superior Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="225">
    <String name="TransparencyObject">Right Temporalis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="226">
    <String name="TransparencyObject">Sternohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="227">
    <String name="TransparencyObject">Sternothyroid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="228">
    <String name="TransparencyObject">Thyrohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="229">
    <String name="TransparencyObject">Thyroid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="230">
    <String name="TransparencyObject">Head Arteries</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="231">
    <String name="TransparencyObject">Head Lymph Nodes</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="232">
    <String name="TransparencyObject">Head Veins</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="233">
    <String name="TransparencyObject">Left Auriculo Temporal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="234">
    <String name="TransparencyObject">Left Buccal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="235">
    <String name="TransparencyObject">Left Greater Auricular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="236">
    <String name="TransparencyObject">Left Greater Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="237">
    <String name="TransparencyObject">Left Infraorbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="238">
    <String name="TransparencyObject">Left Lesser Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="239">
    <String name="TransparencyObject">Left Lingual Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="240">
    <String name="TransparencyObject">Left Mandibular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="241">
    <String name="TransparencyObject">Left Supra Orbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="242">
    <String name="TransparencyObject">Left Trigeminal Ganglion</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="243">
    <String name="TransparencyObject">Right Auriculo Temporal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="244">
    <String name="TransparencyObject">Right Buccal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="245">
    <String name="TransparencyObject">Right Greater Auricular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="246">
    <String name="TransparencyObject">Right Greater Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="247">
    <String name="TransparencyObject">Right Infraorbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="248">
    <String name="TransparencyObject">Right Lesser Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="249">
    <String name="TransparencyObject">Right Lingual Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="250">
    <String name="TransparencyObject">Right Mandibular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="251">
    <String name="TransparencyObject">Right Supra Orbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="252">
    <String name="TransparencyObject">Right Trigeminal Ganglion</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="253">
    <String name="TransparencyObject">Brain</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="254">
    <String name="TransparencyObject">BrainStemMadulaPons</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="255">
    <String name="TransparencyObject">Cerebellum</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="256">
    <String name="TransparencyObject">Chest Manubrium Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="257">
    <String name="TransparencyObject">Clavical</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="258">
    <String name="TransparencyObject">FalxCerebri</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="259">
    <String name="TransparencyObject">FirstRib</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="260">
    <String name="TransparencyObject">Fornix</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="261">
    <String name="TransparencyObject">Hypothalamus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="262">
    <String name="TransparencyObject">LateralGlobusPallidus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="263">
    <String name="TransparencyObject">Left Conoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="264">
    <String name="TransparencyObject">Left Coraco Acromial Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="265">
    <String name="TransparencyObject">Left Infraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="266">
    <String name="TransparencyObject">Left Subscapularis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="267">
    <String name="TransparencyObject">Left Superior Acromio Clavicular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="268">
    <String name="TransparencyObject">Left Superior Transverse Scapular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="269">
    <String name="TransparencyObject">Left Supraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="270">
    <String name="TransparencyObject">Left Teres Major</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="271">
    <String name="TransparencyObject">Left Teres Minor</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="272">
    <String name="TransparencyObject">Left Trapezoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="273">
    <String name="TransparencyObject">LeftScapula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="274">
    <String name="TransparencyObject">Manubrium</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="275">
    <String name="TransparencyObject">MedialGlobusPallidus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="276">
    <String name="TransparencyObject">OpticCanal</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="277">
    <String name="TransparencyObject">PinealGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="278">
    <String name="TransparencyObject">PituitaryGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="279">
    <String name="TransparencyObject">Putamen</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="280">
    <String name="TransparencyObject">Right Conoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="281">
    <String name="TransparencyObject">Right Coraco Acromial Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="282">
    <String name="TransparencyObject">Right Infraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="283">
    <String name="TransparencyObject">Right Subscapularis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="284">
    <String name="TransparencyObject">Right Superior Acromio Clavicular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="285">
    <String name="TransparencyObject">Right Supraspinatous</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="286">
    <String name="TransparencyObject">Right Teres Major</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="287">
    <String name="TransparencyObject">Right Teres Minor</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="288">
    <String name="TransparencyObject">RightScapula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="289">
    <String name="TransparencyObject">Spinal Nerves</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="290">
    <String name="TransparencyObject">Sternocleidomastoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="291">
    <String name="TransparencyObject">SubstantiaNigra</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="292">
    <String name="TransparencyObject">SubthalamicNucleus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="293">
    <String name="TransparencyObject">Thalamus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="294">
    <String name="TransparencyObject">Trapezius</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="295">
    <String name="TransparencyObject">Trapezoid Ligament Left</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="296">
    <String name="TransparencyObject">Trapezoid Ligament Right</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="297">
    <String name="TransparencyObject">Ventricles</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="298">
    <String name="TransparencyObject">Eyebrows and Eyelashes</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="299">
    <String name="TransparencyObject">Left Eye</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="300">
    <String name="TransparencyObject">Right Eye</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="301">
    <String name="TransparencyObject">Skin</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="302">
    <String name="TransparencyObject">Alar Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="303">
    <String name="TransparencyObject">Anterior Atlanto Occip Membrane</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="304">
    <String name="TransparencyObject">Anterior Longitude Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="305">
    <String name="TransparencyObject">Apical Ligament Of Dens</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="306">
    <String name="TransparencyObject">Atlanto Occipital Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="307">
    <String name="TransparencyObject">Atlantoaxial Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="308">
    <String name="TransparencyObject">C1</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="309">
    <String name="TransparencyObject">C2</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="310">
    <String name="TransparencyObject">C3</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="311">
    <String name="TransparencyObject">C4</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="312">
    <String name="TransparencyObject">C5</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="313">
    <String name="TransparencyObject">C6</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="314">
    <String name="TransparencyObject">C7</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="315">
    <String name="TransparencyObject">Intertransverse Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="316">
    <String name="TransparencyObject">Intervertebral Disc Capsules</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="317">
    <String name="TransparencyObject">Ligamenta Flava</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="318">
    <String name="TransparencyObject">Nuchal Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="319">
    <String name="TransparencyObject">Posterior Atlanto Occip Memb</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="320">
    <String name="TransparencyObject">Posterior Longitude Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="321">
    <String name="TransparencyObject">T1</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="322">
    <String name="TransparencyObject">Tectorial Membrane</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="323">
    <String name="TransparencyObject">Transverse Ligament Of Atlas</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="324">
    <String name="TransparencyObject">VDiscC2C3</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="325">
    <String name="TransparencyObject">VDiscC3C4</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="326">
    <String name="TransparencyObject">VDiscC4C5</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="327">
    <String name="TransparencyObject">VDiscC5C6</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="328">
    <String name="TransparencyObject">VDiscC6C7</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="329">
    <String name="TransparencyObject">Zygapophysial Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="330">
    <String name="TransparencyObject">Tooth 1</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="331">
    <String name="TransparencyObject">Tooth 2</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="332">
    <String name="TransparencyObject">Tooth 3</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="333">
    <String name="TransparencyObject">Tooth 4</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="334">
    <String name="TransparencyObject">Tooth 5</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="335">
    <String name="TransparencyObject">Tooth 6</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="336">
    <String name="TransparencyObject">Tooth 7</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="337">
    <String name="TransparencyObject">Tooth 8</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="338">
    <String name="TransparencyObject">Tooth 9</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="339">
    <String name="TransparencyObject">Tooth 10</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="340">
    <String name="TransparencyObject">Tooth 11</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="341">
    <String name="TransparencyObject">Tooth 12</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="342">
    <String name="TransparencyObject">Tooth 13</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="343">
    <String name="TransparencyObject">Tooth 14</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="344">
    <String name="TransparencyObject">Tooth 15</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="345">
    <String name="TransparencyObject">Tooth 16</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="346">
    <String name="TransparencyObject">Tooth 17</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="347">
    <String name="TransparencyObject">Tooth 18</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="348">
    <String name="TransparencyObject">Tooth 19</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="349">
    <String name="TransparencyObject">Tooth 20</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="350">
    <String name="TransparencyObject">Tooth 21</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="351">
    <String name="TransparencyObject">Tooth 22</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="352">
    <String name="TransparencyObject">Tooth 23</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="353">
    <String name="TransparencyObject">Tooth 24</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="354">
    <String name="TransparencyObject">Tooth 25</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="355">
    <String name="TransparencyObject">Tooth 26</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="356">
    <String name="TransparencyObject">Tooth 27</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="357">
    <String name="TransparencyObject">Tooth 28</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="358">
    <String name="TransparencyObject">Tooth 29</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="359">
    <String name="TransparencyObject">Tooth 30</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="360">
    <String name="TransparencyObject">Tooth 31</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="361">
    <String name="TransparencyObject">Tooth 32</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="362">
    <String name="TransparencyObject">Left TMJ Disc</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="363">
    <String name="TransparencyObject">Right TMJ Disc</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.EditableLayerState, Standalone" id="186">
    <String name="Name">TopCameraLayers</String>
    <Saveable name="Entry0" id="187" />
    <Saveable name="Entry1" id="188" />
    <Saveable name="Entry2" id="189" />
    <Saveable name="Entry3" id="190" />
    <Saveable name="Entry4" id="191" />
    <Saveable name="Entry5" id="192" />
    <Saveable name="Entry6" id="193" />
    <Saveable name="Entry7" id="194" />
    <Saveable name="Entry8" id="195" />
    <Saveable name="Entry9" id="196" />
    <Saveable name="Entry10" id="197" />
    <Saveable name="Entry11" id="198" />
    <Saveable name="Entry12" id="199" />
    <Saveable name="Entry13" id="200" />
    <Saveable name="Entry14" id="201" />
    <Saveable name="Entry15" id="202" />
    <Saveable name="Entry16" id="203" />
    <Saveable name="Entry17" id="204" />
    <Saveable name="Entry18" id="205" />
    <Saveable name="Entry19" id="206" />
    <Saveable name="Entry20" id="207" />
    <Saveable name="Entry21" id="208" />
    <Saveable name="Entry22" id="209" />
    <Saveable name="Entry23" id="210" />
    <Saveable name="Entry24" id="211" />
    <Saveable name="Entry25" id="212" />
    <Saveable name="Entry26" id="213" />
    <Saveable name="Entry27" id="214" />
    <Saveable name="Entry28" id="215" />
    <Saveable name="Entry29" id="216" />
    <Saveable name="Entry30" id="217" />
    <Saveable name="Entry31" id="218" />
    <Saveable name="Entry32" id="219" />
    <Saveable name="Entry33" id="220" />
    <Saveable name="Entry34" id="221" />
    <Saveable name="Entry35" id="222" />
    <Saveable name="Entry36" id="223" />
    <Saveable name="Entry37" id="224" />
    <Saveable name="Entry38" id="225" />
    <Saveable name="Entry39" id="226" />
    <Saveable name="Entry40" id="227" />
    <Saveable name="Entry41" id="228" />
    <Saveable name="Entry42" id="229" />
    <Saveable name="Entry43" id="230" />
    <Saveable name="Entry44" id="231" />
    <Saveable name="Entry45" id="232" />
    <Saveable name="Entry46" id="233" />
    <Saveable name="Entry47" id="234" />
    <Saveable name="Entry48" id="235" />
    <Saveable name="Entry49" id="236" />
    <Saveable name="Entry50" id="237" />
    <Saveable name="Entry51" id="238" />
    <Saveable name="Entry52" id="239" />
    <Saveable name="Entry53" id="240" />
    <Saveable name="Entry54" id="241" />
    <Saveable name="Entry55" id="242" />
    <Saveable name="Entry56" id="243" />
    <Saveable name="Entry57" id="244" />
    <Saveable name="Entry58" id="245" />
    <Saveable name="Entry59" id="246" />
    <Saveable name="Entry60" id="247" />
    <Saveable name="Entry61" id="248" />
    <Saveable name="Entry62" id="249" />
    <Saveable name="Entry63" id="250" />
    <Saveable name="Entry64" id="251" />
    <Saveable name="Entry65" id="252" />
    <Saveable name="Entry66" id="253" />
    <Saveable name="Entry67" id="254" />
    <Saveable name="Entry68" id="255" />
    <Saveable name="Entry69" id="256" />
    <Saveable name="Entry70" id="257" />
    <Saveable name="Entry71" id="258" />
    <Saveable name="Entry72" id="259" />
    <Saveable name="Entry73" id="260" />
    <Saveable name="Entry74" id="261" />
    <Saveable name="Entry75" id="262" />
    <Saveable name="Entry76" id="263" />
    <Saveable name="Entry77" id="264" />
    <Saveable name="Entry78" id="265" />
    <Saveable name="Entry79" id="266" />
    <Saveable name="Entry80" id="267" />
    <Saveable name="Entry81" id="268" />
    <Saveable name="Entry82" id="269" />
    <Saveable name="Entry83" id="270" />
    <Saveable name="Entry84" id="271" />
    <Saveable name="Entry85" id="272" />
    <Saveable name="Entry86" id="273" />
    <Saveable name="Entry87" id="274" />
    <Saveable name="Entry88" id="275" />
    <Saveable name="Entry89" id="276" />
    <Saveable name="Entry90" id="277" />
    <Saveable name="Entry91" id="278" />
    <Saveable name="Entry92" id="279" />
    <Saveable name="Entry93" id="280" />
    <Saveable name="Entry94" id="281" />
    <Saveable name="Entry95" id="282" />
    <Saveable name="Entry96" id="283" />
    <Saveable name="Entry97" id="284" />
    <Saveable name="Entry98" id="285" />
    <Saveable name="Entry99" id="286" />
    <Saveable name="Entry100" id="287" />
    <Saveable name="Entry101" id="288" />
    <Saveable name="Entry102" id="289" />
    <Saveable name="Entry103" id="290" />
    <Saveable name="Entry104" id="291" />
    <Saveable name="Entry105" id="292" />
    <Saveable name="Entry106" id="293" />
    <Saveable name="Entry107" id="294" />
    <Saveable name="Entry108" id="295" />
    <Saveable name="Entry109" id="296" />
    <Saveable name="Entry110" id="297" />
    <Saveable name="Entry111" id="298" />
    <Saveable name="Entry112" id="299" />
    <Saveable name="Entry113" id="300" />
    <Saveable name="Entry114" id="301" />
    <Saveable name="Entry115" id="302" />
    <Saveable name="Entry116" id="303" />
    <Saveable name="Entry117" id="304" />
    <Saveable name="Entry118" id="305" />
    <Saveable name="Entry119" id="306" />
    <Saveable name="Entry120" id="307" />
    <Saveable name="Entry121" id="308" />
    <Saveable name="Entry122" id="309" />
    <Saveable name="Entry123" id="310" />
    <Saveable name="Entry124" id="311" />
    <Saveable name="Entry125" id="312" />
    <Saveable name="Entry126" id="313" />
    <Saveable name="Entry127" id="314" />
    <Saveable name="Entry128" id="315" />
    <Saveable name="Entry129" id="316" />
    <Saveable name="Entry130" id="317" />
    <Saveable name="Entry131" id="318" />
    <Saveable name="Entry132" id="319" />
    <Saveable name="Entry133" id="320" />
    <Saveable name="Entry134" id="321" />
    <Saveable name="Entry135" id="322" />
    <Saveable name="Entry136" id="323" />
    <Saveable name="Entry137" id="324" />
    <Saveable name="Entry138" id="325" />
    <Saveable name="Entry139" id="326" />
    <Saveable name="Entry140" id="327" />
    <Saveable name="Entry141" id="328" />
    <Saveable name="Entry142" id="329" />
    <Saveable name="Entry143" id="330" />
    <Saveable name="Entry144" id="331" />
    <Saveable name="Entry145" id="332" />
    <Saveable name="Entry146" id="333" />
    <Saveable name="Entry147" id="334" />
    <Saveable name="Entry148" id="335" />
    <Saveable name="Entry149" id="336" />
    <Saveable name="Entry150" id="337" />
    <Saveable name="Entry151" id="338" />
    <Saveable name="Entry152" id="339" />
    <Saveable name="Entry153" id="340" />
    <Saveable name="Entry154" id="341" />
    <Saveable name="Entry155" id="342" />
    <Saveable name="Entry156" id="343" />
    <Saveable name="Entry157" id="344" />
    <Saveable name="Entry158" id="345" />
    <Saveable name="Entry159" id="346" />
    <Saveable name="Entry160" id="347" />
    <Saveable name="Entry161" id="348" />
    <Saveable name="Entry162" id="349" />
    <Saveable name="Entry163" id="350" />
    <Saveable name="Entry164" id="351" />
    <Saveable name="Entry165" id="352" />
    <Saveable name="Entry166" id="353" />
    <Saveable name="Entry167" id="354" />
    <Saveable name="Entry168" id="355" />
    <Saveable name="Entry169" id="356" />
    <Saveable name="Entry170" id="357" />
    <Saveable name="Entry171" id="358" />
    <Saveable name="Entry172" id="359" />
    <Saveable name="Entry173" id="360" />
    <Saveable name="Entry174" id="361" />
    <Saveable name="Entry175" id="362" />
    <Saveable name="Entry176" id="363" />
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="365">
    <String name="TransparencyObject">Airway</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="366">
    <String name="TransparencyObject">Nasal Cartilage</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="367">
    <String name="TransparencyObject">Nasal Cavity</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="368">
    <String name="TransparencyObject">Pharynx</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="369">
    <String name="TransparencyObject">Septal Cartilage</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="370">
    <String name="TransparencyObject">Hyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="371">
    <String name="TransparencyObject">Left Eminence</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="372">
    <String name="TransparencyObject">Mandible</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="373">
    <String name="TransparencyObject">Maxillary Sinus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="374">
    <String name="TransparencyObject">Right Eminence</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="375">
    <String name="TransparencyObject">Skull</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="376">
    <String name="TransparencyObject">Skull Interior</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="377">
    <String name="TransparencyObject">LeftParotidGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="378">
    <String name="TransparencyObject">LeftSubmandibularSublingualGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="379">
    <String name="TransparencyObject">Lips</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="380">
    <String name="TransparencyObject">Mandible Gums</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="381">
    <String name="TransparencyObject">Maxilla Gums</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="382">
    <String name="TransparencyObject">RightParotidGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="383">
    <String name="TransparencyObject">RightSubmandibularSublingualGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="384">
    <String name="TransparencyObject">Tongue</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="385">
    <String name="TransparencyObject">Uvula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="386">
    <String name="TransparencyObject">Digastric Belly</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="387">
    <String name="TransparencyObject">Geniohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="388">
    <String name="TransparencyObject">Left Digastric</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="389">
    <String name="TransparencyObject">Left Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="390">
    <String name="TransparencyObject">Left Lateral Superior Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="391">
    <String name="TransparencyObject">Left Masseter</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="392">
    <String name="TransparencyObject">Left Medial Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="393">
    <String name="TransparencyObject">Left Stylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="394">
    <String name="TransparencyObject">Left Temporalis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="395">
    <String name="TransparencyObject">Mylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="396">
    <String name="TransparencyObject">Omohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="397">
    <String name="TransparencyObject">Right Digastric</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="398">
    <String name="TransparencyObject">Right Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="399">
    <String name="TransparencyObject">Right Masseter</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="400">
    <String name="TransparencyObject">Right Medial Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="401">
    <String name="TransparencyObject">Right Stylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="402">
    <String name="TransparencyObject">Right Superior Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="403">
    <String name="TransparencyObject">Right Temporalis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="404">
    <String name="TransparencyObject">Sternohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="405">
    <String name="TransparencyObject">Sternothyroid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="406">
    <String name="TransparencyObject">Thyrohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="407">
    <String name="TransparencyObject">Thyroid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="408">
    <String name="TransparencyObject">Head Arteries</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="409">
    <String name="TransparencyObject">Head Lymph Nodes</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="410">
    <String name="TransparencyObject">Head Veins</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="411">
    <String name="TransparencyObject">Left Auriculo Temporal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="412">
    <String name="TransparencyObject">Left Buccal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="413">
    <String name="TransparencyObject">Left Greater Auricular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="414">
    <String name="TransparencyObject">Left Greater Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="415">
    <String name="TransparencyObject">Left Infraorbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="416">
    <String name="TransparencyObject">Left Lesser Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="417">
    <String name="TransparencyObject">Left Lingual Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="418">
    <String name="TransparencyObject">Left Mandibular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="419">
    <String name="TransparencyObject">Left Supra Orbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="420">
    <String name="TransparencyObject">Left Trigeminal Ganglion</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="421">
    <String name="TransparencyObject">Right Auriculo Temporal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="422">
    <String name="TransparencyObject">Right Buccal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="423">
    <String name="TransparencyObject">Right Greater Auricular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="424">
    <String name="TransparencyObject">Right Greater Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="425">
    <String name="TransparencyObject">Right Infraorbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="426">
    <String name="TransparencyObject">Right Lesser Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="427">
    <String name="TransparencyObject">Right Lingual Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="428">
    <String name="TransparencyObject">Right Mandibular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="429">
    <String name="TransparencyObject">Right Supra Orbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="430">
    <String name="TransparencyObject">Right Trigeminal Ganglion</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="431">
    <String name="TransparencyObject">Brain</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="432">
    <String name="TransparencyObject">BrainStemMadulaPons</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="433">
    <String name="TransparencyObject">Cerebellum</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="434">
    <String name="TransparencyObject">Chest Manubrium Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="435">
    <String name="TransparencyObject">Clavical</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="436">
    <String name="TransparencyObject">FalxCerebri</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="437">
    <String name="TransparencyObject">FirstRib</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="438">
    <String name="TransparencyObject">Fornix</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="439">
    <String name="TransparencyObject">Hypothalamus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="440">
    <String name="TransparencyObject">LateralGlobusPallidus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="441">
    <String name="TransparencyObject">Left Conoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="442">
    <String name="TransparencyObject">Left Coraco Acromial Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="443">
    <String name="TransparencyObject">Left Infraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="444">
    <String name="TransparencyObject">Left Subscapularis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="445">
    <String name="TransparencyObject">Left Superior Acromio Clavicular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="446">
    <String name="TransparencyObject">Left Superior Transverse Scapular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="447">
    <String name="TransparencyObject">Left Supraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="448">
    <String name="TransparencyObject">Left Teres Major</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="449">
    <String name="TransparencyObject">Left Teres Minor</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="450">
    <String name="TransparencyObject">Left Trapezoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="451">
    <String name="TransparencyObject">LeftScapula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="452">
    <String name="TransparencyObject">Manubrium</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="453">
    <String name="TransparencyObject">MedialGlobusPallidus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="454">
    <String name="TransparencyObject">OpticCanal</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="455">
    <String name="TransparencyObject">PinealGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="456">
    <String name="TransparencyObject">PituitaryGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="457">
    <String name="TransparencyObject">Putamen</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="458">
    <String name="TransparencyObject">Right Conoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="459">
    <String name="TransparencyObject">Right Coraco Acromial Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="460">
    <String name="TransparencyObject">Right Infraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="461">
    <String name="TransparencyObject">Right Subscapularis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="462">
    <String name="TransparencyObject">Right Superior Acromio Clavicular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="463">
    <String name="TransparencyObject">Right Supraspinatous</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="464">
    <String name="TransparencyObject">Right Teres Major</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="465">
    <String name="TransparencyObject">Right Teres Minor</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="466">
    <String name="TransparencyObject">RightScapula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="467">
    <String name="TransparencyObject">Spinal Nerves</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="468">
    <String name="TransparencyObject">Sternocleidomastoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="469">
    <String name="TransparencyObject">SubstantiaNigra</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="470">
    <String name="TransparencyObject">SubthalamicNucleus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="471">
    <String name="TransparencyObject">Thalamus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="472">
    <String name="TransparencyObject">Trapezius</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="473">
    <String name="TransparencyObject">Trapezoid Ligament Left</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="474">
    <String name="TransparencyObject">Trapezoid Ligament Right</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="475">
    <String name="TransparencyObject">Ventricles</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="476">
    <String name="TransparencyObject">Eyebrows and Eyelashes</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="477">
    <String name="TransparencyObject">Left Eye</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="478">
    <String name="TransparencyObject">Right Eye</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="479">
    <String name="TransparencyObject">Skin</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="480">
    <String name="TransparencyObject">Alar Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="481">
    <String name="TransparencyObject">Anterior Atlanto Occip Membrane</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="482">
    <String name="TransparencyObject">Anterior Longitude Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="483">
    <String name="TransparencyObject">Apical Ligament Of Dens</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="484">
    <String name="TransparencyObject">Atlanto Occipital Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="485">
    <String name="TransparencyObject">Atlantoaxial Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="486">
    <String name="TransparencyObject">C1</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="487">
    <String name="TransparencyObject">C2</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="488">
    <String name="TransparencyObject">C3</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="489">
    <String name="TransparencyObject">C4</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="490">
    <String name="TransparencyObject">C5</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="491">
    <String name="TransparencyObject">C6</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="492">
    <String name="TransparencyObject">C7</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="493">
    <String name="TransparencyObject">Intertransverse Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="494">
    <String name="TransparencyObject">Intervertebral Disc Capsules</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="495">
    <String name="TransparencyObject">Ligamenta Flava</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="496">
    <String name="TransparencyObject">Nuchal Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="497">
    <String name="TransparencyObject">Posterior Atlanto Occip Memb</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="498">
    <String name="TransparencyObject">Posterior Longitude Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="499">
    <String name="TransparencyObject">T1</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="500">
    <String name="TransparencyObject">Tectorial Membrane</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="501">
    <String name="TransparencyObject">Transverse Ligament Of Atlas</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="502">
    <String name="TransparencyObject">VDiscC2C3</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="503">
    <String name="TransparencyObject">VDiscC3C4</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="504">
    <String name="TransparencyObject">VDiscC4C5</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="505">
    <String name="TransparencyObject">VDiscC5C6</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="506">
    <String name="TransparencyObject">VDiscC6C7</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="507">
    <String name="TransparencyObject">Zygapophysial Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="508">
    <String name="TransparencyObject">Tooth 1</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="509">
    <String name="TransparencyObject">Tooth 2</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="510">
    <String name="TransparencyObject">Tooth 3</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="511">
    <String name="TransparencyObject">Tooth 4</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="512">
    <String name="TransparencyObject">Tooth 5</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="513">
    <String name="TransparencyObject">Tooth 6</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="514">
    <String name="TransparencyObject">Tooth 7</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="515">
    <String name="TransparencyObject">Tooth 8</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="516">
    <String name="TransparencyObject">Tooth 9</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="517">
    <String name="TransparencyObject">Tooth 10</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="518">
    <String name="TransparencyObject">Tooth 11</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="519">
    <String name="TransparencyObject">Tooth 12</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="520">
    <String name="TransparencyObject">Tooth 13</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="521">
    <String name="TransparencyObject">Tooth 14</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="522">
    <String name="TransparencyObject">Tooth 15</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="523">
    <String name="TransparencyObject">Tooth 16</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="524">
    <String name="TransparencyObject">Tooth 17</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="525">
    <String name="TransparencyObject">Tooth 18</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="526">
    <String name="TransparencyObject">Tooth 19</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="527">
    <String name="TransparencyObject">Tooth 20</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="528">
    <String name="TransparencyObject">Tooth 21</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="529">
    <String name="TransparencyObject">Tooth 22</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="530">
    <String name="TransparencyObject">Tooth 23</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="531">
    <String name="TransparencyObject">Tooth 24</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="532">
    <String name="TransparencyObject">Tooth 25</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="533">
    <String name="TransparencyObject">Tooth 26</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="534">
    <String name="TransparencyObject">Tooth 27</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="535">
    <String name="TransparencyObject">Tooth 28</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="536">
    <String name="TransparencyObject">Tooth 29</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="537">
    <String name="TransparencyObject">Tooth 30</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="538">
    <String name="TransparencyObject">Tooth 31</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="539">
    <String name="TransparencyObject">Tooth 32</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="540">
    <String name="TransparencyObject">Left TMJ Disc</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="541">
    <String name="TransparencyObject">Right TMJ Disc</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.EditableLayerState, Standalone" id="364">
    <String name="Name">BottomCameraLayers</String>
    <Saveable name="Entry0" id="365" />
    <Saveable name="Entry1" id="366" />
    <Saveable name="Entry2" id="367" />
    <Saveable name="Entry3" id="368" />
    <Saveable name="Entry4" id="369" />
    <Saveable name="Entry5" id="370" />
    <Saveable name="Entry6" id="371" />
    <Saveable name="Entry7" id="372" />
    <Saveable name="Entry8" id="373" />
    <Saveable name="Entry9" id="374" />
    <Saveable name="Entry10" id="375" />
    <Saveable name="Entry11" id="376" />
    <Saveable name="Entry12" id="377" />
    <Saveable name="Entry13" id="378" />
    <Saveable name="Entry14" id="379" />
    <Saveable name="Entry15" id="380" />
    <Saveable name="Entry16" id="381" />
    <Saveable name="Entry17" id="382" />
    <Saveable name="Entry18" id="383" />
    <Saveable name="Entry19" id="384" />
    <Saveable name="Entry20" id="385" />
    <Saveable name="Entry21" id="386" />
    <Saveable name="Entry22" id="387" />
    <Saveable name="Entry23" id="388" />
    <Saveable name="Entry24" id="389" />
    <Saveable name="Entry25" id="390" />
    <Saveable name="Entry26" id="391" />
    <Saveable name="Entry27" id="392" />
    <Saveable name="Entry28" id="393" />
    <Saveable name="Entry29" id="394" />
    <Saveable name="Entry30" id="395" />
    <Saveable name="Entry31" id="396" />
    <Saveable name="Entry32" id="397" />
    <Saveable name="Entry33" id="398" />
    <Saveable name="Entry34" id="399" />
    <Saveable name="Entry35" id="400" />
    <Saveable name="Entry36" id="401" />
    <Saveable name="Entry37" id="402" />
    <Saveable name="Entry38" id="403" />
    <Saveable name="Entry39" id="404" />
    <Saveable name="Entry40" id="405" />
    <Saveable name="Entry41" id="406" />
    <Saveable name="Entry42" id="407" />
    <Saveable name="Entry43" id="408" />
    <Saveable name="Entry44" id="409" />
    <Saveable name="Entry45" id="410" />
    <Saveable name="Entry46" id="411" />
    <Saveable name="Entry47" id="412" />
    <Saveable name="Entry48" id="413" />
    <Saveable name="Entry49" id="414" />
    <Saveable name="Entry50" id="415" />
    <Saveable name="Entry51" id="416" />
    <Saveable name="Entry52" id="417" />
    <Saveable name="Entry53" id="418" />
    <Saveable name="Entry54" id="419" />
    <Saveable name="Entry55" id="420" />
    <Saveable name="Entry56" id="421" />
    <Saveable name="Entry57" id="422" />
    <Saveable name="Entry58" id="423" />
    <Saveable name="Entry59" id="424" />
    <Saveable name="Entry60" id="425" />
    <Saveable name="Entry61" id="426" />
    <Saveable name="Entry62" id="427" />
    <Saveable name="Entry63" id="428" />
    <Saveable name="Entry64" id="429" />
    <Saveable name="Entry65" id="430" />
    <Saveable name="Entry66" id="431" />
    <Saveable name="Entry67" id="432" />
    <Saveable name="Entry68" id="433" />
    <Saveable name="Entry69" id="434" />
    <Saveable name="Entry70" id="435" />
    <Saveable name="Entry71" id="436" />
    <Saveable name="Entry72" id="437" />
    <Saveable name="Entry73" id="438" />
    <Saveable name="Entry74" id="439" />
    <Saveable name="Entry75" id="440" />
    <Saveable name="Entry76" id="441" />
    <Saveable name="Entry77" id="442" />
    <Saveable name="Entry78" id="443" />
    <Saveable name="Entry79" id="444" />
    <Saveable name="Entry80" id="445" />
    <Saveable name="Entry81" id="446" />
    <Saveable name="Entry82" id="447" />
    <Saveable name="Entry83" id="448" />
    <Saveable name="Entry84" id="449" />
    <Saveable name="Entry85" id="450" />
    <Saveable name="Entry86" id="451" />
    <Saveable name="Entry87" id="452" />
    <Saveable name="Entry88" id="453" />
    <Saveable name="Entry89" id="454" />
    <Saveable name="Entry90" id="455" />
    <Saveable name="Entry91" id="456" />
    <Saveable name="Entry92" id="457" />
    <Saveable name="Entry93" id="458" />
    <Saveable name="Entry94" id="459" />
    <Saveable name="Entry95" id="460" />
    <Saveable name="Entry96" id="461" />
    <Saveable name="Entry97" id="462" />
    <Saveable name="Entry98" id="463" />
    <Saveable name="Entry99" id="464" />
    <Saveable name="Entry100" id="465" />
    <Saveable name="Entry101" id="466" />
    <Saveable name="Entry102" id="467" />
    <Saveable name="Entry103" id="468" />
    <Saveable name="Entry104" id="469" />
    <Saveable name="Entry105" id="470" />
    <Saveable name="Entry106" id="471" />
    <Saveable name="Entry107" id="472" />
    <Saveable name="Entry108" id="473" />
    <Saveable name="Entry109" id="474" />
    <Saveable name="Entry110" id="475" />
    <Saveable name="Entry111" id="476" />
    <Saveable name="Entry112" id="477" />
    <Saveable name="Entry113" id="478" />
    <Saveable name="Entry114" id="479" />
    <Saveable name="Entry115" id="480" />
    <Saveable name="Entry116" id="481" />
    <Saveable name="Entry117" id="482" />
    <Saveable name="Entry118" id="483" />
    <Saveable name="Entry119" id="484" />
    <Saveable name="Entry120" id="485" />
    <Saveable name="Entry121" id="486" />
    <Saveable name="Entry122" id="487" />
    <Saveable name="Entry123" id="488" />
    <Saveable name="Entry124" id="489" />
    <Saveable name="Entry125" id="490" />
    <Saveable name="Entry126" id="491" />
    <Saveable name="Entry127" id="492" />
    <Saveable name="Entry128" id="493" />
    <Saveable name="Entry129" id="494" />
    <Saveable name="Entry130" id="495" />
    <Saveable name="Entry131" id="496" />
    <Saveable name="Entry132" id="497" />
    <Saveable name="Entry133" id="498" />
    <Saveable name="Entry134" id="499" />
    <Saveable name="Entry135" id="500" />
    <Saveable name="Entry136" id="501" />
    <Saveable name="Entry137" id="502" />
    <Saveable name="Entry138" id="503" />
    <Saveable name="Entry139" id="504" />
    <Saveable name="Entry140" id="505" />
    <Saveable name="Entry141" id="506" />
    <Saveable name="Entry142" id="507" />
    <Saveable name="Entry143" id="508" />
    <Saveable name="Entry144" id="509" />
    <Saveable name="Entry145" id="510" />
    <Saveable name="Entry146" id="511" />
    <Saveable name="Entry147" id="512" />
    <Saveable name="Entry148" id="513" />
    <Saveable name="Entry149" id="514" />
    <Saveable name="Entry150" id="515" />
    <Saveable name="Entry151" id="516" />
    <Saveable name="Entry152" id="517" />
    <Saveable name="Entry153" id="518" />
    <Saveable name="Entry154" id="519" />
    <Saveable name="Entry155" id="520" />
    <Saveable name="Entry156" id="521" />
    <Saveable name="Entry157" id="522" />
    <Saveable name="Entry158" id="523" />
    <Saveable name="Entry159" id="524" />
    <Saveable name="Entry160" id="525" />
    <Saveable name="Entry161" id="526" />
    <Saveable name="Entry162" id="527" />
    <Saveable name="Entry163" id="528" />
    <Saveable name="Entry164" id="529" />
    <Saveable name="Entry165" id="530" />
    <Saveable name="Entry166" id="531" />
    <Saveable name="Entry167" id="532" />
    <Saveable name="Entry168" id="533" />
    <Saveable name="Entry169" id="534" />
    <Saveable name="Entry170" id="535" />
    <Saveable name="Entry171" id="536" />
    <Saveable name="Entry172" id="537" />
    <Saveable name="Entry173" id="538" />
    <Saveable name="Entry174" id="539" />
    <Saveable name="Entry175" id="540" />
    <Saveable name="Entry176" id="541" />
  </Saveable>
  <Saveable type="Medical.GUI.TeethAdaptationGUIData, PiperJBO" id="2">
    <Saveable name="&lt;TopCamera&gt;k__BackingField" id="3" />
    <Saveable name="&lt;BottomCamera&gt;k__BackingField" id="4" />
    <Saveable name="&lt;LeftLateralCamera&gt;k__BackingField" id="5" />
    <Saveable name="&lt;RightLateralCamera&gt;k__BackingField" id="6" />
    <Saveable name="&lt;MidlineAnteriorCamera&gt;k__BackingField" id="7" />
    <Saveable name="&lt;AllTeethLayers&gt;k__BackingField" id="8" />
    <Saveable name="&lt;TopCameraLayers&gt;k__BackingField" id="186" />
    <Saveable name="&lt;BottomCameraLayers&gt;k__BackingField" id="364" />
  </Saveable>
  <Saveable type="Medical.ShowTimelineGUIAction, Standalone" id="1">
    <String name="GUIName">PiperJBO.TeethAdaptationGUI</String>
    <Saveable name="GUIData" id="2" />
  </Saveable>
  <Saveable type="Medical.MoveCameraAction, Standalone" id="543">
    <Vector3 name="Translation">0, -10.03284, 47.71947</Vector3>
    <Vector3 name="LookAt">0, -10.03284, 7.857922</Vector3>
    <String name="CameraName">Camera 1</String>
    <Vector3 name="IncludePoint">4.209716, -6.489634, 7.220814</Vector3>
    <Float name="StartTime">0</Float>
    <Float name="Duration">0.5</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="546">
    <String name="TransparencyObject">Airway</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="547">
    <String name="TransparencyObject">Nasal Cartilage</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="548">
    <String name="TransparencyObject">Nasal Cavity</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="549">
    <String name="TransparencyObject">Pharynx</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="550">
    <String name="TransparencyObject">Septal Cartilage</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="551">
    <String name="TransparencyObject">Hyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="552">
    <String name="TransparencyObject">Left Eminence</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="553">
    <String name="TransparencyObject">Mandible</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="554">
    <String name="TransparencyObject">Maxillary Sinus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="555">
    <String name="TransparencyObject">Right Eminence</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="556">
    <String name="TransparencyObject">Skull</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="557">
    <String name="TransparencyObject">Skull Interior</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="558">
    <String name="TransparencyObject">LeftParotidGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="559">
    <String name="TransparencyObject">LeftSubmandibularSublingualGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="560">
    <String name="TransparencyObject">Lips</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="561">
    <String name="TransparencyObject">Mandible Gums</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="562">
    <String name="TransparencyObject">Maxilla Gums</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="563">
    <String name="TransparencyObject">RightParotidGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="564">
    <String name="TransparencyObject">RightSubmandibularSublingualGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="565">
    <String name="TransparencyObject">Tongue</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="566">
    <String name="TransparencyObject">Uvula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="567">
    <String name="TransparencyObject">Digastric Belly</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="568">
    <String name="TransparencyObject">Geniohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="569">
    <String name="TransparencyObject">Left Digastric</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="570">
    <String name="TransparencyObject">Left Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="571">
    <String name="TransparencyObject">Left Lateral Superior Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="572">
    <String name="TransparencyObject">Left Masseter</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="573">
    <String name="TransparencyObject">Left Medial Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="574">
    <String name="TransparencyObject">Left Stylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="575">
    <String name="TransparencyObject">Left Temporalis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="576">
    <String name="TransparencyObject">Mylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="577">
    <String name="TransparencyObject">Omohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="578">
    <String name="TransparencyObject">Right Digastric</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="579">
    <String name="TransparencyObject">Right Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="580">
    <String name="TransparencyObject">Right Masseter</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="581">
    <String name="TransparencyObject">Right Medial Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="582">
    <String name="TransparencyObject">Right Stylohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="583">
    <String name="TransparencyObject">Right Superior Lateral Pterygoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="584">
    <String name="TransparencyObject">Right Temporalis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="585">
    <String name="TransparencyObject">Sternohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="586">
    <String name="TransparencyObject">Sternothyroid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="587">
    <String name="TransparencyObject">Thyrohyoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="588">
    <String name="TransparencyObject">Thyroid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="589">
    <String name="TransparencyObject">Head Arteries</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="590">
    <String name="TransparencyObject">Head Lymph Nodes</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="591">
    <String name="TransparencyObject">Head Veins</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="592">
    <String name="TransparencyObject">Left Auriculo Temporal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="593">
    <String name="TransparencyObject">Left Buccal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="594">
    <String name="TransparencyObject">Left Greater Auricular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="595">
    <String name="TransparencyObject">Left Greater Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="596">
    <String name="TransparencyObject">Left Infraorbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="597">
    <String name="TransparencyObject">Left Lesser Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="598">
    <String name="TransparencyObject">Left Lingual Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="599">
    <String name="TransparencyObject">Left Mandibular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="600">
    <String name="TransparencyObject">Left Supra Orbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="601">
    <String name="TransparencyObject">Left Trigeminal Ganglion</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="602">
    <String name="TransparencyObject">Right Auriculo Temporal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="603">
    <String name="TransparencyObject">Right Buccal Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="604">
    <String name="TransparencyObject">Right Greater Auricular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="605">
    <String name="TransparencyObject">Right Greater Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="606">
    <String name="TransparencyObject">Right Infraorbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="607">
    <String name="TransparencyObject">Right Lesser Occipital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="608">
    <String name="TransparencyObject">Right Lingual Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="609">
    <String name="TransparencyObject">Right Mandibular Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="610">
    <String name="TransparencyObject">Right Supra Orbital Nerve</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="611">
    <String name="TransparencyObject">Right Trigeminal Ganglion</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="612">
    <String name="TransparencyObject">Brain</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="613">
    <String name="TransparencyObject">BrainStemMadulaPons</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="614">
    <String name="TransparencyObject">Cerebellum</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="615">
    <String name="TransparencyObject">Chest Manubrium Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="616">
    <String name="TransparencyObject">Clavical</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="617">
    <String name="TransparencyObject">FalxCerebri</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="618">
    <String name="TransparencyObject">FirstRib</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="619">
    <String name="TransparencyObject">Fornix</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="620">
    <String name="TransparencyObject">Hypothalamus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="621">
    <String name="TransparencyObject">LateralGlobusPallidus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="622">
    <String name="TransparencyObject">Left Conoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="623">
    <String name="TransparencyObject">Left Coraco Acromial Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="624">
    <String name="TransparencyObject">Left Infraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="625">
    <String name="TransparencyObject">Left Subscapularis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="626">
    <String name="TransparencyObject">Left Superior Acromio Clavicular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="627">
    <String name="TransparencyObject">Left Superior Transverse Scapular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="628">
    <String name="TransparencyObject">Left Supraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="629">
    <String name="TransparencyObject">Left Teres Major</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="630">
    <String name="TransparencyObject">Left Teres Minor</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="631">
    <String name="TransparencyObject">Left Trapezoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="632">
    <String name="TransparencyObject">LeftScapula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="633">
    <String name="TransparencyObject">Manubrium</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="634">
    <String name="TransparencyObject">MedialGlobusPallidus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="635">
    <String name="TransparencyObject">OpticCanal</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="636">
    <String name="TransparencyObject">PinealGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="637">
    <String name="TransparencyObject">PituitaryGland</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="638">
    <String name="TransparencyObject">Putamen</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="639">
    <String name="TransparencyObject">Right Conoid Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="640">
    <String name="TransparencyObject">Right Coraco Acromial Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="641">
    <String name="TransparencyObject">Right Infraspinatus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="642">
    <String name="TransparencyObject">Right Subscapularis</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="643">
    <String name="TransparencyObject">Right Superior Acromio Clavicular Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="644">
    <String name="TransparencyObject">Right Supraspinatous</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="645">
    <String name="TransparencyObject">Right Teres Major</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="646">
    <String name="TransparencyObject">Right Teres Minor</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="647">
    <String name="TransparencyObject">RightScapula</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="648">
    <String name="TransparencyObject">Spinal Nerves</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="649">
    <String name="TransparencyObject">Sternocleidomastoid</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="650">
    <String name="TransparencyObject">SubstantiaNigra</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="651">
    <String name="TransparencyObject">SubthalamicNucleus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="652">
    <String name="TransparencyObject">Thalamus</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="653">
    <String name="TransparencyObject">Trapezius</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="654">
    <String name="TransparencyObject">Trapezoid Ligament Left</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="655">
    <String name="TransparencyObject">Trapezoid Ligament Right</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="656">
    <String name="TransparencyObject">Ventricles</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="657">
    <String name="TransparencyObject">Eyebrows and Eyelashes</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="658">
    <String name="TransparencyObject">Left Eye</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="659">
    <String name="TransparencyObject">Right Eye</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="660">
    <String name="TransparencyObject">Skin</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="661">
    <String name="TransparencyObject">Alar Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="662">
    <String name="TransparencyObject">Anterior Atlanto Occip Membrane</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="663">
    <String name="TransparencyObject">Anterior Longitude Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="664">
    <String name="TransparencyObject">Apical Ligament Of Dens</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="665">
    <String name="TransparencyObject">Atlanto Occipital Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="666">
    <String name="TransparencyObject">Atlantoaxial Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="667">
    <String name="TransparencyObject">C1</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="668">
    <String name="TransparencyObject">C2</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="669">
    <String name="TransparencyObject">C3</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="670">
    <String name="TransparencyObject">C4</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="671">
    <String name="TransparencyObject">C5</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="672">
    <String name="TransparencyObject">C6</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="673">
    <String name="TransparencyObject">C7</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="674">
    <String name="TransparencyObject">Intertransverse Ligaments</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="675">
    <String name="TransparencyObject">Intervertebral Disc Capsules</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="676">
    <String name="TransparencyObject">Ligamenta Flava</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="677">
    <String name="TransparencyObject">Nuchal Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="678">
    <String name="TransparencyObject">Posterior Atlanto Occip Memb</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="679">
    <String name="TransparencyObject">Posterior Longitude Ligament</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="680">
    <String name="TransparencyObject">T1</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="681">
    <String name="TransparencyObject">Tectorial Membrane</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="682">
    <String name="TransparencyObject">Transverse Ligament Of Atlas</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="683">
    <String name="TransparencyObject">VDiscC2C3</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="684">
    <String name="TransparencyObject">VDiscC3C4</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="685">
    <String name="TransparencyObject">VDiscC4C5</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="686">
    <String name="TransparencyObject">VDiscC5C6</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="687">
    <String name="TransparencyObject">VDiscC6C7</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="688">
    <String name="TransparencyObject">Zygapophysial Joint Capsule</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="689">
    <String name="TransparencyObject">Tooth 1</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="690">
    <String name="TransparencyObject">Tooth 2</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="691">
    <String name="TransparencyObject">Tooth 3</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="692">
    <String name="TransparencyObject">Tooth 4</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="693">
    <String name="TransparencyObject">Tooth 5</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="694">
    <String name="TransparencyObject">Tooth 6</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="695">
    <String name="TransparencyObject">Tooth 7</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="696">
    <String name="TransparencyObject">Tooth 8</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="697">
    <String name="TransparencyObject">Tooth 9</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="698">
    <String name="TransparencyObject">Tooth 10</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="699">
    <String name="TransparencyObject">Tooth 11</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="700">
    <String name="TransparencyObject">Tooth 12</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="701">
    <String name="TransparencyObject">Tooth 13</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="702">
    <String name="TransparencyObject">Tooth 14</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="703">
    <String name="TransparencyObject">Tooth 15</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="704">
    <String name="TransparencyObject">Tooth 16</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="705">
    <String name="TransparencyObject">Tooth 17</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="706">
    <String name="TransparencyObject">Tooth 18</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="707">
    <String name="TransparencyObject">Tooth 19</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="708">
    <String name="TransparencyObject">Tooth 20</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="709">
    <String name="TransparencyObject">Tooth 21</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="710">
    <String name="TransparencyObject">Tooth 22</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="711">
    <String name="TransparencyObject">Tooth 23</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="712">
    <String name="TransparencyObject">Tooth 24</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="713">
    <String name="TransparencyObject">Tooth 25</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="714">
    <String name="TransparencyObject">Tooth 26</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="715">
    <String name="TransparencyObject">Tooth 27</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="716">
    <String name="TransparencyObject">Tooth 28</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="717">
    <String name="TransparencyObject">Tooth 29</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="718">
    <String name="TransparencyObject">Tooth 30</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="719">
    <String name="TransparencyObject">Tooth 31</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="720">
    <String name="TransparencyObject">Tooth 32</String>
    <Float name="AlphaValue">1</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="721">
    <String name="TransparencyObject">Left TMJ Disc</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerEntry, Standalone" id="722">
    <String name="TransparencyObject">Right TMJ Disc</String>
    <Float name="AlphaValue">0</Float>
  </Saveable>
  <Saveable type="Medical.LayerState, Standalone" id="545">
    <String name="Name" />
    <Saveable name="Entry0" id="546" />
    <Saveable name="Entry1" id="547" />
    <Saveable name="Entry2" id="548" />
    <Saveable name="Entry3" id="549" />
    <Saveable name="Entry4" id="550" />
    <Saveable name="Entry5" id="551" />
    <Saveable name="Entry6" id="552" />
    <Saveable name="Entry7" id="553" />
    <Saveable name="Entry8" id="554" />
    <Saveable name="Entry9" id="555" />
    <Saveable name="Entry10" id="556" />
    <Saveable name="Entry11" id="557" />
    <Saveable name="Entry12" id="558" />
    <Saveable name="Entry13" id="559" />
    <Saveable name="Entry14" id="560" />
    <Saveable name="Entry15" id="561" />
    <Saveable name="Entry16" id="562" />
    <Saveable name="Entry17" id="563" />
    <Saveable name="Entry18" id="564" />
    <Saveable name="Entry19" id="565" />
    <Saveable name="Entry20" id="566" />
    <Saveable name="Entry21" id="567" />
    <Saveable name="Entry22" id="568" />
    <Saveable name="Entry23" id="569" />
    <Saveable name="Entry24" id="570" />
    <Saveable name="Entry25" id="571" />
    <Saveable name="Entry26" id="572" />
    <Saveable name="Entry27" id="573" />
    <Saveable name="Entry28" id="574" />
    <Saveable name="Entry29" id="575" />
    <Saveable name="Entry30" id="576" />
    <Saveable name="Entry31" id="577" />
    <Saveable name="Entry32" id="578" />
    <Saveable name="Entry33" id="579" />
    <Saveable name="Entry34" id="580" />
    <Saveable name="Entry35" id="581" />
    <Saveable name="Entry36" id="582" />
    <Saveable name="Entry37" id="583" />
    <Saveable name="Entry38" id="584" />
    <Saveable name="Entry39" id="585" />
    <Saveable name="Entry40" id="586" />
    <Saveable name="Entry41" id="587" />
    <Saveable name="Entry42" id="588" />
    <Saveable name="Entry43" id="589" />
    <Saveable name="Entry44" id="590" />
    <Saveable name="Entry45" id="591" />
    <Saveable name="Entry46" id="592" />
    <Saveable name="Entry47" id="593" />
    <Saveable name="Entry48" id="594" />
    <Saveable name="Entry49" id="595" />
    <Saveable name="Entry50" id="596" />
    <Saveable name="Entry51" id="597" />
    <Saveable name="Entry52" id="598" />
    <Saveable name="Entry53" id="599" />
    <Saveable name="Entry54" id="600" />
    <Saveable name="Entry55" id="601" />
    <Saveable name="Entry56" id="602" />
    <Saveable name="Entry57" id="603" />
    <Saveable name="Entry58" id="604" />
    <Saveable name="Entry59" id="605" />
    <Saveable name="Entry60" id="606" />
    <Saveable name="Entry61" id="607" />
    <Saveable name="Entry62" id="608" />
    <Saveable name="Entry63" id="609" />
    <Saveable name="Entry64" id="610" />
    <Saveable name="Entry65" id="611" />
    <Saveable name="Entry66" id="612" />
    <Saveable name="Entry67" id="613" />
    <Saveable name="Entry68" id="614" />
    <Saveable name="Entry69" id="615" />
    <Saveable name="Entry70" id="616" />
    <Saveable name="Entry71" id="617" />
    <Saveable name="Entry72" id="618" />
    <Saveable name="Entry73" id="619" />
    <Saveable name="Entry74" id="620" />
    <Saveable name="Entry75" id="621" />
    <Saveable name="Entry76" id="622" />
    <Saveable name="Entry77" id="623" />
    <Saveable name="Entry78" id="624" />
    <Saveable name="Entry79" id="625" />
    <Saveable name="Entry80" id="626" />
    <Saveable name="Entry81" id="627" />
    <Saveable name="Entry82" id="628" />
    <Saveable name="Entry83" id="629" />
    <Saveable name="Entry84" id="630" />
    <Saveable name="Entry85" id="631" />
    <Saveable name="Entry86" id="632" />
    <Saveable name="Entry87" id="633" />
    <Saveable name="Entry88" id="634" />
    <Saveable name="Entry89" id="635" />
    <Saveable name="Entry90" id="636" />
    <Saveable name="Entry91" id="637" />
    <Saveable name="Entry92" id="638" />
    <Saveable name="Entry93" id="639" />
    <Saveable name="Entry94" id="640" />
    <Saveable name="Entry95" id="641" />
    <Saveable name="Entry96" id="642" />
    <Saveable name="Entry97" id="643" />
    <Saveable name="Entry98" id="644" />
    <Saveable name="Entry99" id="645" />
    <Saveable name="Entry100" id="646" />
    <Saveable name="Entry101" id="647" />
    <Saveable name="Entry102" id="648" />
    <Saveable name="Entry103" id="649" />
    <Saveable name="Entry104" id="650" />
    <Saveable name="Entry105" id="651" />
    <Saveable name="Entry106" id="652" />
    <Saveable name="Entry107" id="653" />
    <Saveable name="Entry108" id="654" />
    <Saveable name="Entry109" id="655" />
    <Saveable name="Entry110" id="656" />
    <Saveable name="Entry111" id="657" />
    <Saveable name="Entry112" id="658" />
    <Saveable name="Entry113" id="659" />
    <Saveable name="Entry114" id="660" />
    <Saveable name="Entry115" id="661" />
    <Saveable name="Entry116" id="662" />
    <Saveable name="Entry117" id="663" />
    <Saveable name="Entry118" id="664" />
    <Saveable name="Entry119" id="665" />
    <Saveable name="Entry120" id="666" />
    <Saveable name="Entry121" id="667" />
    <Saveable name="Entry122" id="668" />
    <Saveable name="Entry123" id="669" />
    <Saveable name="Entry124" id="670" />
    <Saveable name="Entry125" id="671" />
    <Saveable name="Entry126" id="672" />
    <Saveable name="Entry127" id="673" />
    <Saveable name="Entry128" id="674" />
    <Saveable name="Entry129" id="675" />
    <Saveable name="Entry130" id="676" />
    <Saveable name="Entry131" id="677" />
    <Saveable name="Entry132" id="678" />
    <Saveable name="Entry133" id="679" />
    <Saveable name="Entry134" id="680" />
    <Saveable name="Entry135" id="681" />
    <Saveable name="Entry136" id="682" />
    <Saveable name="Entry137" id="683" />
    <Saveable name="Entry138" id="684" />
    <Saveable name="Entry139" id="685" />
    <Saveable name="Entry140" id="686" />
    <Saveable name="Entry141" id="687" />
    <Saveable name="Entry142" id="688" />
    <Saveable name="Entry143" id="689" />
    <Saveable name="Entry144" id="690" />
    <Saveable name="Entry145" id="691" />
    <Saveable name="Entry146" id="692" />
    <Saveable name="Entry147" id="693" />
    <Saveable name="Entry148" id="694" />
    <Saveable name="Entry149" id="695" />
    <Saveable name="Entry150" id="696" />
    <Saveable name="Entry151" id="697" />
    <Saveable name="Entry152" id="698" />
    <Saveable name="Entry153" id="699" />
    <Saveable name="Entry154" id="700" />
    <Saveable name="Entry155" id="701" />
    <Saveable name="Entry156" id="702" />
    <Saveable name="Entry157" id="703" />
    <Saveable name="Entry158" id="704" />
    <Saveable name="Entry159" id="705" />
    <Saveable name="Entry160" id="706" />
    <Saveable name="Entry161" id="707" />
    <Saveable name="Entry162" id="708" />
    <Saveable name="Entry163" id="709" />
    <Saveable name="Entry164" id="710" />
    <Saveable name="Entry165" id="711" />
    <Saveable name="Entry166" id="712" />
    <Saveable name="Entry167" id="713" />
    <Saveable name="Entry168" id="714" />
    <Saveable name="Entry169" id="715" />
    <Saveable name="Entry170" id="716" />
    <Saveable name="Entry171" id="717" />
    <Saveable name="Entry172" id="718" />
    <Saveable name="Entry173" id="719" />
    <Saveable name="Entry174" id="720" />
    <Saveable name="Entry175" id="721" />
    <Saveable name="Entry176" id="722" />
  </Saveable>
  <Saveable type="Medical.LayerChangeAction, Standalone" id="544">
    <Saveable name="LayerState" id="545" />
    <String name="TransparencyState">Camera 1</String>
    <Float name="StartTime">0</Float>
    <Float name="Duration">0.5</Float>
  </Saveable>
  <Saveable type="Medical.ActionSequencer`1[[Medical.TimelineAction, Standalone, Version=2.0.0.2381, Culture=neutral, PublicKeyToken=null]], Standalone" id="542">
    <Saveable name="Actions0" id="543" />
    <Saveable name="Actions1" id="544" />
  </Saveable>
  <Saveable type="Medical.Timeline, Standalone" id="0">
    <Saveable name="PreActions0" id="1" />
    <Saveable name="Sequencer" id="542" />
  </Saveable>
</Save>